// Decompiled with JetBrains decompiler
// Type: Telerik.Sitefinity.Services.Web.Services.ModuleType
// Assembly: Telerik.Sitefinity, Version=13.3.7600.0, Culture=neutral, PublicKeyToken=b28c218413bdf563
// MVID: 39C4B52A-B559-4D9C-97D9-CCCF73C3738E
// Assembly location: C:\Programs\Sitefinity\ProjectManager_13_3_7600\_EmptyProject\bin\Telerik.Sitefinity.dll

namespace Telerik.Sitefinity.Services.Web.Services
{
  /// <summary>Defines the types of the module</summary>
  internal enum ModuleType
  {
    /// <summary>Part of the Sitefinity installation</summary>
    Static,
    /// <summary>Generated by the ModuleBuilder</summary>
    Dynamic,
  }
}
