Type.registerNamespace("Telerik.Sitefinity.Web.UI");
Telerik.Sitefinity.Web.UI.PagesSelector=function(element){this._element=element;
this._tabstrip=null;
this._pageSelector=null;
this._extPagesSelector=null;
this._doneButton=null;
this._cancelButton=null;
this._bindOnLoad=null;
this.__currentPanelDelegate=null;
this._onloadDelegate=null;
this._selectionChangedDelegate=null;
this._doneSelectingDelegate=null;
this._pageSelector_selectionAppliedDelegate=null;
this._cancelDelegate=null;
this.PANEL_THIS_SITE="panelThisSite";
this.PANEL_OTHER_SITES="panelOtherSites";
this._selectedPanel=this.PANEL_THIS_SITE;
this._selectedPages=null;
this._selectedInternalPages=null;
this._selectedExternalPages=null;
this._onTabSelectedDelegate=null;
this._uiCulture=null;
Telerik.Sitefinity.Web.UI.PagesSelector.initializeBase(this,[element]);
};
Telerik.Sitefinity.Web.UI.PagesSelector.prototype={initialize:function(){Telerik.Sitefinity.Web.UI.PagesSelector.callBaseMethod(this,"initialize");
if(this._onloadDelegate==null){this._onloadDelegate=Function.createDelegate(this,this._onload);
}Sys.Application.add_load(this._onloadDelegate);
this._doneSelectingDelegate=Function.createDelegate(this,this._onDoneSelecting);
$addHandler(this.get_doneButton(),"click",this._doneSelectingDelegate);
this._cancelDelegate=Function.createDelegate(this,this._onCancel);
$addHandler(this.get_cancelButton(),"click",this._cancelDelegate);
if(this._selectionChangedDelegate==null){this._selectionChangedDelegate=Function.createDelegate(this,this._selectionChanged);
}if(this._pageSelector_selectionAppliedDelegate==null){this._pageSelector_selectionAppliedDelegate=Function.createDelegate(this,this._pageSelector_selectionApplied);
}var pageSelector=this.get_pageSelector();
pageSelector.set_uiCulture(this.get_uiCulture());
pageSelector.add_selectionChanged(this._selectionChangedDelegate);
pageSelector.add_selectionApplied(this._pageSelector_selectionAppliedDelegate);
pageSelector.set_bindOnLoad(false);
if(this.get_tabstrip()){this._onTabSelectedDelegate=Function.createDelegate(this,this._onTabSelected);
this._tabstrip.add_tabSelected(this._onTabSelectedDelegate);
}},dispose:function(){if(this._onloadDelegate){Sys.Application.remove_load(this._onloadDelegate);
delete this._onloadDelegate;
}if(this._doneSelectingDelegate){$removeHandler(this.get_doneButton(),"click",this._doneSelectingDelegate);
delete this._doneSelectingDelegate;
}if(this._cancelDelegate){$removeHandler(this.get_cancelButton(),"click",this._cancelDelegate);
delete this._cancelDelegate;
}if(this._selectionChangedDelegate){this.get_pageSelector().remove_selectionChanged(this._selectionChangedDelegate);
delete this._selectionChangedDelegate;
}if(this._pageSelector_selectionAppliedDelegate){this.get_pageSelector().remove_selectionApplied(this._pageSelector_selectionAppliedDelegate);
delete this._pageSelector_selectionAppliedDelegate;
}if(this._currentPanelDelegate){delete this._currentPanelDelegate;
}if(this.get_tabstrip()){this._tabstrip.remove_tabSelected(this._onTabSelectedDelegate);
delete this._onTabSelectedDelegate;
}Telerik.Sitefinity.Web.UI.PagesSelector.callBaseMethod(this,"dispose");
},dataBind:function(query){this.get_pageSelector().dataBind(query);
},clearSelection:function(){},getSelectedItems:function(){var items=this.get_pageSelector().get_selectedItems();
var result=[];
if(items){for(var i=0,l=items.length;
i<l;
i++){var item=items[i];
if(item.TitlesPath){result.push({Id:item.Id,Title:item.TitlesPath});
}else{result.push({Id:item.Id,Title:item.Title.Value});
}}}items=this.get_extPagesSelector().get_selectedItems();
if(items){for(var i=0,l=items.length;
i<l;
i++){var item=items[i];
result.push({Id:item.Id,Title:item.Title,Url:item.Url});
}}return result;
},setSelectedItems:function(items){this._selectedPages=items;
var selectedInternalPages=[];
var selectedExternalPages=[];
var hasSelectedExternalPages=false;
for(var i=0;
i<items.length;
i++){var item=items[i];
if(item.Id){selectedInternalPages.push(item);
}else{selectedExternalPages.push(item);
hasSelectedExternalPages=true;
}}this._selectedInternalPages=selectedInternalPages;
this._selectedExternalPages=selectedExternalPages;
this.get_pageSelector().set_selectedItems(selectedInternalPages);
this.get_pageSelector().dataBind("");
this.get_extPagesSelector().set_selectedItems(selectedExternalPages);
if(hasSelectedExternalPages==true){var elm=jQuery(this.get_element()).find("input[value='"+this.PANEL_OTHER_SITES+"']");
elm.attr("checked","checked");
this._showPanel(this.PANEL_OTHER_SITES);
}},_onTabSelected:function(){dialogBase.resizeToContent();
},add_selectionChanged:function(delegate){this.get_events().addHandler("selectionChanged",delegate);
},remove_selectionChanged:function(delegate){this.get_events().removeHandler("selectionChanged",delegate);
},add_doneClientSelection:function(delegate){this.get_events().addHandler("doneClientSelection",delegate);
},remove_doneClientSelection:function(delegate){this.get_events().removeHandler("doneClientSelection",delegate);
},add_selectionApplied:function(handler){this.get_events().addHandler("selectionApplied",handler);
},remove_selectionApplied:function(handler){this.get_events().removeHandler("selectionApplied",handler);
},_raiseSelectionApplied:function(args){var handler=this.get_events().getHandler("selectionApplied");
if(handler){handler(this,args);
}},_setRadioClickHandler:function(groupName,delegate){jQuery(this.get_element()).find("input[name='"+groupName+"']").click(delegate);
},_onload:function(){var query=null;
if(this._bindOnLoad){this.dataBind(query);
}},_clickedCurrentPanel:function(sender){this._hideAllPanels();
this._selectedPanel=sender.target.value;
this._showPanel(sender.target.value);
},_hideAllPanels:function(){jQuery(this.get_element()).find("#Panels div[id^='panel']").hide();
},_showPanel:function(panelId){jQuery(this.get_element()).find("#Panels #"+panelId).show();
},_selectionChanged:function(sender,args){var selectedItems=args;
},_pageSelector_selectionApplied:function(sender,args){this._raiseSelectionApplied(args);
},_doneSelecting:function(cancel){var h=this.get_events().getHandler("doneClientSelection");
if(h){if(cancel){h(null,true);
}else{var selectedPages=this.getSelectedItems();
h(selectedPages,false);
}}},_onDoneSelecting:function(){this._doneSelecting(false);
},_onCancel:function(){this._doneSelecting(true);
},get_element:function(){return this._element;
},set_element:function(value){this._element=value;
},get_tabstrip:function(){return this._tabstrip;
},set_tabstrip:function(value){this._tabstrip=value;
},get_doneButton:function(){return this._doneButton;
},set_doneButton:function(value){this._doneButton=value;
},get_cancelButton:function(){return this._cancelButton;
},set_cancelButton:function(value){this._cancelButton=value;
},get_pageSelector:function(){return this._pageSelector;
},set_pageSelector:function(value){this._pageSelector=value;
},get_extPagesSelector:function(){return this._extPagesSelector;
},set_extPagesSelector:function(value){this._extPagesSelector=value;
},get_uiCulture:function(){return this._uiCulture;
},set_uiCulture:function(value){this._uiCulture=value;
},get_selectedItem:function(){var selectedItems=null;
return null;
},set_selectedItemId:function(value){this._selectedItemId=value;
},get_selectedItemId:function(){var selectedItem=this.get_selectedItem();
if(selectedItem){return selectedItem.Id;
}return this._selectedItemId;
},get_selectedPanel:function(){return this._selectedPanel;
}};
Telerik.Sitefinity.Web.UI.PagesSelector.registerClass("Telerik.Sitefinity.Web.UI.PagesSelector",Sys.UI.Control);
