requirejs.config({paths:{text:"Telerik.Sitefinity.Resources.Scripts.RequireJS.text",FieldsFactory:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Scripts.FieldsFactory",EditableField:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Scripts.EditableField",ContentRepository:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.Scripts.ContentRepository",WorkflowPanel:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.Scripts.WorkflowPanel",WorkflowPanelTemplate:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.Templates.WorkflowPanel.sfhtml",ShortText:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Scripts.ShortText",LongText:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Scripts.LongText",EditableContainer:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.Scripts.EditableContainer",EditableContainerTemplate:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.Templates.EditableContainer.sfhtml",EditableWindowField:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Scripts.EditableWindowField",EditableWindowFieldTemplate:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Templates.EditableWindowField.sfhtml",YesNo:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Scripts.YesNo",YesNoTemplate:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Templates.YesNo.sfhtml",ChoicesRadioButtons:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Scripts.ChoicesRadioButtons",ChoicesRadioButtonsTemplate:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Templates.ChoicesRadioButtons.sfhtml",ChoicesDropDown:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Scripts.ChoicesDropDown",ChoicesDropDownTemplate:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Templates.ChoicesDropDown.sfhtml",ChoicesCheckBoxes:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Scripts.ChoicesCheckBoxes",ChoicesCheckBoxesTemplate:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Templates.ChoicesCheckBoxes.sfhtml",FlatTaxon:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Scripts.FlatTaxon",FlatTaxonTemplate:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Templates.FlatTaxon.sfhtml",HierarchicalTaxon:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Scripts.HierarchicalTaxon",ImageControl:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Scripts.ImageControl",ImageControlTemplate:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Templates.ImageControl.sfhtml",ImageField:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Scripts.ImageField",ImageFieldTemplate:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Templates.ImageField.sfhtml",ImageSelector:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Scripts.ImageSelector",ImageSelectorTemplate:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Templates.ImageSelector.sfhtml",DialogBase:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Scripts.DialogBase",DialogBaseTemplate:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Templates.DialogBase.sfhtml",ContentSelectorBase:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Scripts.ContentSelectorBase",HierarchicalContentSelector:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Scripts.HierarchicalContentSelector",HierarchicalContentSelectorTemplate:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Templates.HierarchicalContentSelector.sfhtml",FlatContentSelector:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Scripts.FlatContentSelector",FlatContentSelectorTemplate:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Templates.FlatContentSelector.sfhtml",LibrariesSelector:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Scripts.LibrariesSelector",ProvidersSelector:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Scripts.ProvidersSelector",FlatTaxonSelector:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Scripts.FlatTaxonSelector",HierarchicalTaxonSelector:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Scripts.HierarchicalTaxonSelector",HierarchicalTaxonSelectorDataTemplate:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Templates.HierarchicalTaxonSelectorDataTemplate.sfhtml",HyperLinkManager:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Scripts.HyperLinkManager",HyperLinkManagerTemplate:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Templates.HyperLinkManagerTemplate.sfhtml",PageSelector:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Scripts.PageSelector",ImageEditor:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Scripts.ImageEditor",ImageEditorTemplate:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Templates.ImageEditor.sfhtml",DetailViewEditingWindow:"Telerik.Sitefinity.Web.RequireJSModules.Scripts.DetailViewEditingWindow",DateTime:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Scripts.DateTime",DateTimeTemplate:"Telerik.Sitefinity.Web.UI.PublicControls.InlineEditing.EditableControls.Templates.DateTime.sfhtml"},waitSeconds:0});
var InlineEditingManager=function(){var that=this;
this.editableContainers=[];
this.containers=$("[data-sf-type]").filter(function(){return $(this).data("sf-type");
});
this.viewModel=kendo.observable({pageId:"",baseUrl:"",pageUrl:"",serviceUrl:"",imageServiceUrl:"",flatTaxonServiceUrl:"",currentUICulture:"",siteBaseUrl:"",navigatingAwayMessage:"",redirectToRoot:false,isPageLocked:false,isEditingEnabled:false,isMenuVisible:false,showDraftItems:false,toggleMenu:function(e){e.preventDefault();
this.set("isMenuVisible",!this.isMenuVisible);
if(this.isMenuVisible){$(".sfInlineEditingPageMenu").addClass("sfInlineEditMenuOpened");
}else{$(".sfInlineEditingPageMenu").removeClass("sfInlineEditMenuOpened");
}},hideMenu:function(e){this.set("isMenuVisible",false);
$(".sfInlineEditingPageMenu").removeClass("sfInlineEditMenuOpened");
},logOut:function(){var url="";
if(this.siteBaseUrl&&this.siteBaseUrl!="/"){if(this.siteBaseUrl.endsWith("/")){url+=this.siteBaseUrl.substr(0,this.siteBaseUrl.length-1);
}else{url+=this.siteBaseUrl;
}if(!url.startsWith("/")){url="/"+url;
}}url+="/Sitefinity/SignOut?sts_signout=true&redirect=false";
$.ajax({type:"GET",url:url,async:false,statusCode:{200:function(response,textStatus,jqXHR){window.location.href=window.location.href.replace("/Action/InEdit","");
},302:function(data){window.location.href=window.location.href.replace("/Action/InEdit","");
}}});
},editThisPage:function(e){that.editThisPage();
},cancelEditThisPage:function(e){that.cancelEditThisPage();
},isInEditMode:function(e){return that.isInEditMode();
},isNotInEditMode:function(e){return !that.isInEditMode();
},switchViewMode:function(e){that.switchViewMode();
}});
this.constants={enabledCookieValue:"enabled",actionEditUrlSegment:"Action/InEdit",actionPreviewUrlSegment:"Action/Preview"};
this.workflowMenu=null;
this.contentRepository=null;
};
InlineEditingManager.prototype={initialize:function(){var itemId,itemType,that=this;
kendo.bind($(".sfInlineEditingPageMenu"),this.viewModel);
if(this.isInEditMode()){this.disableLinks();
require.config({baseUrl:this.viewModel.get("baseUrl"),config:{text:{onXhr:function(xhr,url){if(that.viewModel.currentUICulture){xhr.setRequestHeader("SF_UI_CULTURE",that.viewModel.currentUICulture);
}}}}});
window.onbeforeunload=function(){var hasChanges=false;
$.each(that.editableContainers,function(index,item){hasChanges|=item.needsCleanUp;
});
if(hasChanges){return that.viewModel.navigatingAwayMessage;
}};
this.viewModel.set("showDraftItems",true);
require(["text!"+this.viewModel.serviceUrl+"/configuration"],function(reqJsPathsConfig){eval(reqJsPathsConfig);
require(["ContentRepository","WorkflowPanel"],function(ContentRepository,WorkflowPanel){that.contentRepository=new ContentRepository({serviceUrl:that.viewModel.serviceUrl,pageId:that.viewModel.pageId,currentUICulture:that.viewModel.currentUICulture,imageServiceUrl:that.viewModel.imageServiceUrl,flatTaxonServiceUrl:that.viewModel.flatTaxonServiceUrl});
that.workflowMenu=new WorkflowPanel({contentRepository:that.contentRepository,validator:that.validator});
$(that.workflowMenu).on("commandExecuted",function(event,params){if(params.reload){that.exitEditMode();
}});
require(["EditableContainer","text!EditableContainerTemplate!strip"],function(EditableContainer,htmlTemplate){$.each(that.containers,function(index,item){itemId=$(item).data("sf-id");
itemType=$(item).data("sf-type");
providerName=$(item).data("sf-provider");
var editableContainer=new EditableContainer({element:$(item),itemId:itemId,itemType:itemType,providerName:providerName,siteBaseUrl:that.viewModel.siteBaseUrl,onEdit:function(container){that.workflowMenu.set_currentlyEditedContainer(container);
},onCancelEdit:function(){that.workflowMenu.hide();
},onStopEdit:function(container){that.workflowMenu.stopEditingContainer(container);
},contentRepository:that.contentRepository,isPageLocked:that.viewModel.isPageLocked});
that.editableContainers.push(editableContainer);
that.workflowMenu.add_editableContainer(editableContainer);
});
that.contentRepository.getEditableContainersAdditionalInfo(that.editableContainers,that.viewModel.pageId,function(data,textStatus,jqXHR){var containerData={};
that.workflowMenu.set_additionalInfo(data);
$.each(that.editableContainers,function(index,container){containerData=$.grep(data.ContainersInfo,function(item,index){return container.itemId===item.ItemId;
});
container.initialize(htmlTemplate,containerData[0]);
that.setFieldValidation(container,containerData[0]);
});
that.workflowMenu.show(this);
});
});
});
});
}else{this.viewModel.set("showDraftItems",this.isInPreviewMode());
}},setFieldValidation:function(container,containerData){$.each(container.fields,function(index,field){var currentField=$(field),currentContainerData=$.grep(containerData.Fields,function(item,index){return currentField.data("sf-field")===item.Name;
});
for(var propertyName in currentContainerData[0]){switch(propertyName.toLowerCase()){case"requiredviolationmessage":currentField.attr("data-required-msg",currentContainerData[0][propertyName]);
break;
case"minlengthviolationmessage":currentField.attr("data-minlength-msg",currentContainerData[0][propertyName]);
break;
case"maxlengthviolationmessage":currentField.attr("data-maxlength-msg",currentContainerData[0][propertyName]);
break;
default:currentField.attr(propertyName,currentContainerData[0][propertyName]);
}}});
},editThisPage:function(){if(this.isInEditMode()){$.each(this.editableContainers,function(index,item){item.enableEditing();
});
}else{var url=encodeURI(decodeURI(window.location.href));
if(this.isInPreviewMode()){url=url.replace(this.constants.actionPreviewUrlSegment,"");
}window.location.href=this.getUrl(url,this.constants.actionEditUrlSegment);
}},cancelEditThisPage:function(){if(this.isInEditMode()){this.workflowMenu.exitEditing();
}},exitEditMode:function(){var replacementPart=this.constants.actionEditUrlSegment;
var redirectToRootValue=(typeof this.viewModel.redirectToRoot!=="boolean")?Boolean.parse(this.viewModel.redirectToRoot):this.viewModel.redirectToRoot;
if(redirectToRootValue){replacementPart=this.viewModel.pageUrl+"/"+replacementPart;
}window.location.href=window.location.href.replace(replacementPart,"");
},isInEditMode:function(){return window.location.href.indexOf(this.constants.actionEditUrlSegment)>-1;
},isInPreviewMode:function(){return window.location.href.indexOf(this.constants.actionPreviewUrlSegment)>-1;
},switchViewMode:function(){if(this.viewModel.get("showDraftItems")&&window.location.href.indexOf(this.constants.actionPreviewUrlSegment)<0){window.location.href=this.getUrl(window.location.href,this.constants.actionPreviewUrlSegment);
}else{window.location.href=window.location.href.replace(this.constants.actionPreviewUrlSegment,"");
}},getUrl:function(url,urlSegment){var resultUrl="",segment=urlSegment;
var urlLow=url.toLowerCase();
var pageUrlLow=this.viewModel.pageUrl.toLowerCase();
if(urlLow.indexOf(pageUrlLow)===-1){segment=this.viewModel.pageUrl+"/"+urlSegment;
}if(url.indexOf("/?")>-1){resultUrl=url.replace("?",segment+"/?");
}else{if(url.indexOf("?")>-1){resultUrl=url.replace("?","/"+segment+"?");
}else{if(url.indexOf("/#")>-1){resultUrl=url.replace("#",segment+"/#");
}else{if(url.indexOf("#")>-1){resultUrl=url.replace("#","/"+segment+"#");
}else{if(url.lastIndexOf("/")===url.length-1){resultUrl=url+segment;
}else{resultUrl=url+"/"+segment;
}}}}}return decodeURI(resultUrl);
},disableLinks:function(){var links=$("a");
jQuery.each(links,function(index,link){var parent=$(link).parents("[data-sf-ftype]");
if(parent.length>0){parent=parent[0];
}var parentTypeAttribute=$(parent).attr("data-sf-ftype");
var hrefElement=$(link).attr("href");
var permLink=$(link).attr("data-sf-permlink");
var isPermLink=permLink&&permLink!="";
var validHrefElement=hrefElement&&hrefElement!=""&&hrefElement!="javascript:void(0);"&&!isPermLink;
if(parentTypeAttribute&&parentTypeAttribute!="ShortText"&&parentTypeAttribute!="LongText"&&validHrefElement){$(link).removeAttr("href");
}});
}};
(function($){$(document).ready(function(){var inlineEditingManager=new InlineEditingManager();
inlineEditingManager.initialize();
});
$.fn.loading=function(show){var loading=this.find(">.k-loading-mask");
show?loading.length||(loading=$('<div class="k-loading-mask" data-sf-ignore><span class="k-loading-text">Loading...</span><div class="k-loading-image"></div><div class="k-loading-color"></div></div>').width(this.outerWidth()).height(this.outerHeight()).prependTo(this)):loading&&loading.remove();
};
}(jQuery));
kendo.data.binders.serverValue=kendo.data.Binder.extend({init:function(element,bindings,options){kendo.data.Binder.fn.init.call(this,element,bindings,options);
var binding=this.bindings.serverValue;
binding.source[binding.path]=$(this.element).val();
},refresh:function(){var binding=this.bindings.serverValue;
$(this.element).val(binding.source[binding.path]);
}});
kendo.data.binders.keyUp=kendo.data.Binder.extend({init:function(element,bindings,options){kendo.data.Binder.fn.init.call(this,element,bindings,options);
var binding=this.bindings.keyUp;
$(element).bind("keyup",function(e){if(typeof binding.source[binding.path]==="function"){binding.source[binding.path](this,e);
}});
},refresh:function(){}});
kendo.data.binders.widget.keyUp=kendo.data.Binder.extend({init:function(element,bindings,options){kendo.data.Binder.fn.init.call(this,element,bindings,options);
var binding=this.bindings.keyUp;
if(element.options.name=="MultiSelect"){$(element.element).parent().find("input").bind("keyup",function(e){binding.source.multiSelectKeyUp=e;
binding.get();
});
}},refresh:function(){}});
if(!Array.prototype.indexOf){Array.prototype.indexOf=function(elt){var len=this.length;
var from=Number(arguments[1])||0;
from=(from<0)?Math.ceil(from):Math.floor(from);
if(from<0){from+=len;
}for(;
from<len;
from++){if(from in this&&this[from]===elt){return from;
}}return -1;
};
}if(!Array.prototype.compare){Array.prototype.compare=function(array){if(!array){return false;
}if(this.length!=array.length){return false;
}for(var i=0;
i<this.length;
i++){if(this[i] instanceof Array&&array[i] instanceof Array){if(!this[i].compare(array[i])){return false;
}}else{if(this[i]!=array[i]){var hasSameProps=true;
for(var property in this[i]){if(this[i][property]!=array[i][property]){hasSameProps=false;
break;
}}if(!hasSameProps){return false;
}}}}return true;
};
}if(!Object.create){Object.create=(function(){function F(){}return function(o){if(arguments.length!=1){throw new Error("Object.create implementation only accepts one parameter.");
}F.prototype=o;
return new F();
};
})();
}