var detailFormView=null;
function OnDetailViewLoaded(sender,args){detailFormView=sender;
resetForm();
var behaviorField=findFieldControl("BehaviorField");
behaviorField.add_valueChanged(function(){if(behaviorField.get_value()=="TransformLayout"){switchToLayoutTransformMode();
}else{switchToMiniSiteMode();
}});
}function resetForm(){switchToLayoutTransformMode();
}function switchToLayoutTransformMode(){var siteSelectionSection=findSection("SiteSelection");
$(siteSelectionSection.get_element()).hide();
var cssSelectorSection=findSection("CssSelector");
$(cssSelectorSection.get_element()).show();
var layoutTransformationSection=findSection("LayoutTransformationSection");
$(layoutTransformationSection.get_element()).show();
}function switchToMiniSiteMode(){var siteSelectionSection=findSection("SiteSelection");
$(siteSelectionSection.get_element()).show();
var cssSelectorSection=findSection("CssSelector");
$(cssSelectorSection.get_element()).hide();
var layoutTransformationSection=findSection("LayoutTransformationSection");
$(layoutTransformationSection.get_element()).hide();
}function findSection(sectionName){var section=null;
var sectionIds=detailFormView.get_sectionIds();
for(var s=0;
s<sectionIds.length;
s++){section=$find(sectionIds[s]);
if(section&&section.get_name()==sectionName){return section;
}}return section;
}function findFieldControl(fieldControlName){var fieldControl=null;
var fieldControlsIds=detailFormView.get_fieldControlIds();
for(var f=0;
f<fieldControlsIds.length;
f++){fieldControl=$find(fieldControlsIds[f]);
if(fieldControl&&fieldControl.get_fieldName()==fieldControlName){return fieldControl;
}}return fieldControl;
}