Type.registerNamespace("Telerik.Sitefinity.Web.UI");
Type._registerScript("LanguageSelectorDesigner.js",["IControlDesigner.js"]);
Type.registerNamespace("Telerik.Sitefinity.Localization.Web.UI.Designers");
Telerik.Sitefinity.Localization.Web.UI.Designers.LanguageSelectorDesigner=function(element){Telerik.Sitefinity.Localization.Web.UI.Designers.LanguageSelectorDesigner.initializeBase(this,[element]);
this._propertyEditor=null;
this._controlData=null;
this._includeCurrentCheckbox=null;
this._selectorTypeChangedDelegate=null;
this._noTranslationActionChangedDelegate=null;
this._includeCurrentChangedDelegate=null;
};
Telerik.Sitefinity.Localization.Web.UI.Designers.LanguageSelectorDesigner.prototype={initialize:function(){Telerik.Sitefinity.Localization.Web.UI.Designers.LanguageSelectorDesigner.callBaseMethod(this,"initialize");
$(this).on("unload",function(e){jQuery.event.remove(this);
jQuery.removeData(this);
});
this._selectorTypeChangedDelegate=Function.createDelegate(this,this._selectorTypeChanged);
this._setRadioClickHandler("SelectorType",this._selectorTypeChangedDelegate);
this._noTranslationActionChangedDelegate=Function.createDelegate(this,this._noTranslationActionChanged);
this._setRadioClickHandler("ActionType",this._noTranslationActionChangedDelegate);
this._includeCurrentChangedDelegate=Function.createDelegate(this,this._includeCurrentChanged);
this._includeCurrentCheckbox.add_valueChanged(this._includeCurrentChangedDelegate);
},dispose:function(){if(this._selectorTypeChangedDelegate){delete this._selectorTypeChangedDelegate;
}if(this._noTranslationActionChangedDelegate){delete this._noTranslationActionChangedDelegate;
}if(this._includeCurrentChangedDelegate){this._includeCurrentCheckbox.remove_valueChanged(this._includeCurrentChangedDelegate);
delete this._includeCurrentChangedDelegate;
}Telerik.Sitefinity.Localization.Web.UI.Designers.LanguageSelectorDesigner.callBaseMethod(this,"dispose");
},refreshUI:function(){var controlData=this.get_controlData();
if(!controlData){return;
}this._clickRadioChoice("SelectorType",controlData.SelectorType);
this._clickRadioChoice("ActionType",controlData.MissingTranslationAction);
this.get_includeCurrentCheckbox().set_value(controlData.ShowCurrentLanguage);
},applyChanges:function(){},_selectorTypeChanged:function(sender){this.get_controlData().SelectorType=sender.target.value;
},_noTranslationActionChanged:function(sender){this.get_controlData().MissingTranslationAction=sender.target.value;
},_includeCurrentChanged:function(){this.get_controlData().ShowCurrentLanguage=this.get_includeCurrentCheckbox().get_value();
},_setRadioClickHandler:function(groupName,delegate){jQuery(this.get_element()).find("input[name='"+groupName+"']").click(delegate);
},_getRadioChoice:function(groupName,value){return jQuery(this.get_element()).find("input[name='"+groupName+"'][value='"+value+"']").get(0);
},_clickRadioChoice:function(groupName,value){return jQuery(this.get_element()).find("input[name='"+groupName+"'][value='"+value+"']").click();
},get_controlData:function(){return this.get_propertyEditor().get_control();
},get_propertyEditor:function(){return this._propertyEditor;
},set_propertyEditor:function(value){this._propertyEditor=value;
},get_includeCurrentCheckbox:function(){return this._includeCurrentCheckbox;
},set_includeCurrentCheckbox:function(value){this._includeCurrentCheckbox=value;
}};
Telerik.Sitefinity.Localization.Web.UI.Designers.LanguageSelectorDesigner.registerClass("Telerik.Sitefinity.Localization.Web.UI.Designers.LanguageSelectorDesigner",Telerik.Sitefinity.Web.UI.ControlDesign.ControlDesignerBase);
