Type.registerNamespace("Telerik.Sitefinity.Web.UI");
Telerik.Sitefinity.Web.UI.MetaTypeStructureEditorDialog=function(element){this._metaTypeEditorID=null;
this._saveAndCloseButtonID=null;
this._cancelButtonID=null;
this._metaTypeEditor=null;
this._saveAndCloseButton=null;
this._cancelButton=null;
Telerik.Sitefinity.Web.UI.MetaTypeStructureEditorDialog.initializeBase(this,[element]);
};
Telerik.Sitefinity.Web.UI.MetaTypeStructureEditorDialog.prototype={initialize:function(){Telerik.Sitefinity.Web.UI.MetaTypeStructureEditorDialog.callBaseMethod(this,"initialize");
Sys.Application.add_load(Function.createDelegate(this,this.onload));
this._saveAndCloseButton=$get(this._saveAndCloseButtonID);
this._cancelButton=$get(this._cancelButtonID);
},dispose:function(){Telerik.Sitefinity.Web.UI.MetaTypeStructureEditorDialog.callBaseMethod(this,"dispose");
},onload:function(){this._metaTypeEditor=$find(this._metaTypeEditorID);
this._clickSaveDelegate=Function.createDelegate(this,this._saveAndClose);
this._clickCancelDelegate=Function.createDelegate(this,this._closeWindow);
$addHandler(this._saveAndCloseButton,"click",this._clickSaveDelegate);
$addHandler(this._cancelButton,"click",this._clickCancelDelegate);
},_saveAndClose:function(){try{var value=this._metaTypeEditor.get_dynamicTypeObject();
this._closeMe(value);
}catch(err){}},_closeWindow:function(){this._closeMe(null);
},_closeMe:function(closeArgument){var dialog=dialogBase.get_radWindow();
dialog.close(closeArgument);
}};
Telerik.Sitefinity.Web.UI.MetaTypeStructureEditorDialog.registerClass("Telerik.Sitefinity.Web.UI.MetaTypeStructureEditorDialog",Telerik.Sitefinity.Web.UI.AjaxDialogBase);
