Type.registerNamespace("Telerik.Sitefinity.Modules.Libraries.Web.UI.Designers");
Telerik.Sitefinity.Modules.Libraries.Web.UI.Designers.DocumentSelectorDesignerView=function(element){Telerik.Sitefinity.Modules.Libraries.Web.UI.Designers.DocumentSelectorDesignerView.initializeBase(this,[element]);
this._mediaContentSelector=null;
this._selectedDataItem=null;
this._itemSelectDelegate=null;
};
Telerik.Sitefinity.Modules.Libraries.Web.UI.Designers.DocumentSelectorDesignerView.prototype={initialize:function(){Telerik.Sitefinity.Modules.Libraries.Web.UI.Designers.DocumentSelectorDesignerView.callBaseMethod(this,"initialize");
this._itemSelectDelegate=Function.createDelegate(this,this._itemSelect);
this.get_mediaContentSelector().add_onItemSelectCommand(this._itemSelectDelegate);
$(this).on("unload",function(e){jQuery.event.remove(this);
jQuery.removeData(this);
});
},dispose:function(){Telerik.Sitefinity.Modules.Libraries.Web.UI.Designers.DocumentSelectorDesignerView.callBaseMethod(this,"dispose");
if(this._itemSelectDelegate){if(this.get_mediaContentSelector()){this.get_mediaContentSelector().remove_onItemSelectCommand(this._itemSelectDelegate);
}delete this._itemSelectDelegate;
}},refreshUI:function(){this.get_parentDesigner().set_saveButtonEnabled(false);
},applyChanges:function(){if(this.get_selectedDataItem()){this.get_controlData().DocumentId=this.get_selectedDataItem().Id;
}},rebind:function(providerName){this.get_mediaContentSelector()._provider=providerName;
this.get_mediaContentSelector()._initializeLists();
this.get_parentDesigner().set_saveButtonEnabled(false);
},isItemSelected:function(){return !!this.get_selectedDataItem();
},_itemSelect:function(sender,args){if(!args.get_dataItem().IsFolder){this.set_selectedDataItem(args.get_dataItem());
this.get_parentDesigner().set_saveButtonEnabled(this.isItemSelected());
}},get_parentDesigner:function(){return this._parentDesigner;
},set_parentDesigner:function(value){if(this._parentDesigner!=value){this._parentDesigner=value;
this.raisePropertyChanged("parentDesigner");
}},get_controlData:function(){return this.get_parentDesigner().get_propertyEditor().get_control();
},get_mediaContentSelector:function(){return this._mediaContentSelector;
},set_mediaContentSelector:function(value){this._mediaContentSelector=value;
},get_selectedDataItem:function(){return this._selectedDataItem;
},set_selectedDataItem:function(value){this._selectedDataItem=value;
}};
Telerik.Sitefinity.Modules.Libraries.Web.UI.Designers.DocumentSelectorDesignerView.registerClass("Telerik.Sitefinity.Modules.Libraries.Web.UI.Designers.DocumentSelectorDesignerView",Sys.UI.Control,Telerik.Sitefinity.Web.UI.ControlDesign.IDesignerViewControl);
