Type.registerNamespace("Telerik.Sitefinity.Modules.Libraries.Web.UI.Designers");
Telerik.Sitefinity.Modules.Libraries.Web.UI.Designers.MediaContentSelectorsDesignerView=function(element){Telerik.Sitefinity.Modules.Libraries.Web.UI.Designers.MediaContentSelectorsDesignerView.initializeBase(this,[element]);
this._parentDesigner=null;
this._allItemsRadio=null;
this._libraryRadio=null;
this._uploadRadio=null;
this._selectLibraryButtonClientID=null;
this._selecLibraryButton=null;
this._folderSelector=null;
this._selectedLibrary=null;
this._selectedLibraryTitle=null;
this._selectedLibraryId=null;
this._haveLibraries=null;
this._sortingField=null;
this._currentMasterViewName=null;
this._uploadDialogUrl=null;
this._uploadButton=null;
this._backPhrase=null;
this._isInAdvancedMode=null;
this._propertyEditor=null;
this._uploadDialog=null;
this._filterSelector=null;
this._btnNarrowSelection=null;
this._narrowSelection=null;
this._radioClickedDelegate=null;
this._filterRadioClickDelegate=null;
this._doneSelectingLibraryDelegate=null;
this._openLibrarySelectorDelegate=null;
this._openUploadDialogDelegate=null;
this._uploadDialogPageLoadDelegate=null;
this._uploadDialogCloseDelegate=null;
this._beforeDialogCloseDelegate=null;
this._btnNarrowSelectionClickDelegate=null;
this._selectorTag=null;
this._dialog=null;
this._providersSelector=null;
this._providersSelectorClickedDelegate=null;
this._noContentSelectedLabel=null;
this._selectLibraryButtonWrapper=null;
this._includesChildLibraryItemsLabel=null;
this._includesChildLibraryItems=null;
};
Telerik.Sitefinity.Modules.Libraries.Web.UI.Designers.MediaContentSelectorsDesignerView.prototype={initialize:function(){Telerik.Sitefinity.Modules.Libraries.Web.UI.Designers.MediaContentSelectorsDesignerView.callBaseMethod(this,"initialize");
this._isInAdvancedMode=false;
this._selectLibraryButtonClientID="selectLibraryButton";
this._selectLibraryButton=$get(this._selectLibraryButtonClientID);
this._radioClickedDelegate=Function.createDelegate(this,this._radioClicked);
$addHandler(this._libraryRadio,"click",this._radioClickedDelegate);
$addHandler(this._allItemsRadio,"click",this._radioClickedDelegate);
$addHandler(this._uploadRadio,"click",this._radioClickedDelegate);
this._openUploadDialogDelegate=Function.createDelegate(this,this._openUploadDialog);
$addHandler(this._uploadButton,"click",this._openUploadDialogDelegate);
this._openLibrarySelectorDelegate=Function.createDelegate(this,this._openLibrarySelector);
$addHandler(this._selectLibraryButton,"click",this._openLibrarySelectorDelegate);
this._doneSelectingLibraryDelegate=Function.createDelegate(this,this._selectLibrary);
this._folderSelector.add_doneClientSelection(this._doneSelectingLibraryDelegate);
this._beforeDialogCloseDelegate=Function.createDelegate(this,this._beforeDialogCloseHandler);
this._propertyEditor=this.get_parent().get_parent().get_parent().get_parent();
this._propertyEditor.get_radWindow().add_beforeClose(this._beforeDialogCloseDelegate);
this._filterRadioClickDelegate=Function.createDelegate(this,this._setContentFilter);
this.get_radioChoices().click(this._filterRadioClickDelegate);
if(this._btnNarrowSelection){this._btnNarrowSelectionClickDelegate=Function.createDelegate(this,this._btnNarrowSelectionClick);
$addHandler(this._btnNarrowSelection,"click",this._btnNarrowSelectionClickDelegate);
}if(this._providersSelector){this._providersSelectorClickedDelegate=Function.createDelegate(this,this._handleProvidersChanged);
this._providersSelector.add_onProviderSelected(this._providersSelectorClickedDelegate);
}this._dialog=jQuery(this._selectorTag).dialog({autoOpen:false,modal:false,width:355,closeOnEscape:true,resizable:false,draggable:false,classes:{"ui-dialog":"sfZIndexL"}});
},dispose:function(){Telerik.Sitefinity.Modules.Libraries.Web.UI.Designers.MediaContentSelectorsDesignerView.callBaseMethod(this,"dispose");
if(this._radioClickedDelegate){$removeHandler(this._libraryRadio,"click",this._radioClickedDelegate);
$removeHandler(this._allItemsRadio,"click",this._radioClickedDelegate);
$removeHandler(this._uploadRadio,"click",this._radioClickedDelegate);
delete this._radioClickedDelegate;
}if(this._openLibrarySelectorDelegate){$removeHandler(this._selectLibraryButton,"click",this._openLibrarySelectorDelegate);
delete this._openLibrarySelectorDelegate;
}if(this._doneSelectingLibraryDelegate){this.get_folderSelector().remove_doneClientSelection(this._doneSelectingLibraryDelegate);
delete this._doneSelectingLibraryDelegate;
}if(this._openUploadDialogDelegate){delete this._openUploadDialogDelegate;
}if(this._uploadDialogPageLoadDelegate){delete this._uploadDialogPageLoadDelegate;
}if(this._beforeDialogCloseDelegate){this._propertyEditor.get_radWindow().remove_beforeClose(this._beforeDialogCloseDelegate);
delete this._beforeDialogCloseDelegate;
}if(this._uploadDialogCloseDelegate){this._uploadDialog.remove_beforeClose(this._uploadDialogCloseDelegate);
delete this._uploadDialogCloseDelegate;
}if(this._filterRadioClickDelegate){this.get_radioChoices().unbind("click",this._filterRadioClickDelegate);
delete this._filterRadioClickDelegate;
}if(this._btnNarrowSelection){$removeHandler(this._btnNarrowSelection,"click",this._btnNarrowSelectionClickDelegate);
delete this._btnNarrowSelectionClickDelegate;
}if(this._providersSelector){this._providersSelector.remove_onProviderSelected(this._providersSelectorClickedDelegate);
delete this._providersSelectorClickedDelegate;
}},_openLibrarySelector:function(){var parentId=this.get_currentMasterView().ItemsParentId;
if(parentId!=Telerik.Sitefinity.getEmptyGuid()){this.get_folderSelector().get_foldersGenericSelector().set_selectedItemIds([parentId]);
}this.get_folderSelector().set_includesChildLibraryItems(this._includesChildLibraryItems);
this.get_folderSelector().dataBind();
this._dialog.dialog("open");
jQuery("body > form").hide();
dialogBase.resizeToContent();
},_openUploadDialog:function(){var dialogManager=GetDialogManager();
var dialog=dialogManager.getDialogByName("uploadDialog");
this._uploadDialog=dialog;
dialog.setUrl(this._uploadDialogUrl);
var providerName=this.get_folderSelector().get_providerName();
var params={IsEditable:true,providerName:providerName};
var dialogContext=this._getDialogContext("upload",null,null,dialog,params,"uploadDialog");
if(this._uploadDialogPageLoadDelegate==null){this._uploadDialogPageLoadDelegate=Function.createDelegate(this,this._uploadDialogPageLoad);
dialog.add_pageLoad(this._uploadDialogPageLoadDelegate);
}if(this._uploadDialogCloseDelegate==null){this._uploadDialogCloseDelegate=Function.createDelegate(this,this._uploadDialogClose);
dialog.add_beforeClose(this._uploadDialogCloseDelegate);
}this._propertyEditor.set_forceReload(true);
dialogManager.openDialog("uploadDialog",this,dialogContext);
if(!dialog.isMaximized()){dialog.maximize();
}this._isInAdvancedMode=true;
},_uploadDialogPageLoad:function(sender,args){sender._iframe.contentWindow.jQuery(".sfBack").html(this._backPhrase);
},_uploadDialogClose:function(sender,args){this._isInAdvancedMode=false;
},_getDialogContext:function(commandName,dataItem,itemsList,dialog,params,key,commandArgument,additionalProperties){if(additionalProperties){commandArgument=jQuery.extend(true,commandArgument,additionalProperties);
}return{commandName:commandName,dataItem:dataItem,itemsList:itemsList,dialog:dialog,params:params,key:key,commandArgument:commandArgument};
},_beforeDialogCloseHandler:function(sender,args){if(this._isInAdvancedMode){args.set_cancel(true);
var dialogManager=GetDialogManager();
var dialog=dialogManager.getDialogByName("uploadDialog");
dialog.Close();
this._isInAdvancedMode=false;
}},_selectLibrary:function(args){this._dialog.dialog("close");
jQuery("body > form").show();
dialogBase.resizeToContent();
if(args===null){return;
}var selectedItems=this.get_folderSelector().get_foldersGenericSelector().get_selectedItems();
if(selectedItems!=null){if(selectedItems.length>0){var selectedTitle=selectedItems[0].Path!=null?selectedItems[0].Path:selectedItems[0].Title;
if(selectedTitle.hasOwnProperty("Value")){this.get_selectedLibrary().innerText=selectedTitle.Value;
}else{this.get_selectedLibrary().innerText=selectedTitle;
}jQuery(this.get_selectedLibrary()).show();
this._selectedLibraryId=selectedItems[0].Id;
this._includesChildLibraryItems=this.get_folderSelector().get_includesChildLibraryItems();
if(this.get_includesChildLibraryItemsLabel()){jQuery(this.get_includesChildLibraryItemsLabel()).toggle(this._includesChildLibraryItems);
}}}},_radioClicked:function(sender,args){switch(sender.target){case this._libraryRadio:$("#uploadWrapper").hide();
$("#selectLibraryWrapper").show();
if(this._selectedLibraryTitle){this.get_selectedLibrary().innerHTML=this._selectedLibraryTitle;
}break;
case this._allItemsRadio:$("#selectLibraryWrapper").hide();
$("#uploadWrapper").hide();
break;
case this._uploadRadio:$("#selectLibraryWrapper").hide();
$("#uploadWrapper").show();
break;
}dialogBase.resizeToContent();
},_resolvePropertyPath:function(property){var viewPath="ControlDefinition.Views['"+this.get_currentViewName()+"']";
var propertyPath=viewPath+"."+property;
return propertyPath;
},_getCurrentView:function(parent){var settingsDesignerViewId=parent.get_designerViewsMap()["imageGallerySettingsDesignerView"];
if(!settingsDesignerViewId){settingsDesignerViewId=parent.get_designerViewsMap()["videoGallerySettingsDesignerView"];
}var settingsDesignerView=$find(settingsDesignerViewId);
if(settingsDesignerView){return settingsDesignerView.get_currentView();
}return null;
},_handleProvidersChanged:function(sender,args){var controlData=this.get_controlData();
var oldProviderName=controlData.ControlDefinition.ProviderName;
if(controlData.ControlDefinition.hasOwnProperty("ProviderName")){controlData.ControlDefinition.ProviderName=args.ProviderName;
}this.get_folderSelector().set_providerName(args.ProviderName);
this.get_folderSelector().dataBind();
if(args.ProviderName!=oldProviderName){this._resetViewOnProvidersChanged();
}dialogBase.resizeToContent();
},_resetViewOnProvidersChanged:function(){this._allItemsRadio.click();
$(this._allItemsRadio).attr("checked",true);
$(this.get_selectedLibrary()).text(this._noContentSelectedLabel);
this._selectedLibraryTitle=null;
this.get_currentMasterView().ItemsParentId=Telerik.Sitefinity.getEmptyGuid();
this._selectedLibraryId=Telerik.Sitefinity.getEmptyGuid();
if(this.get_selectLibraryButtonWrapper()){$(this.get_selectLibraryButtonWrapper()).show();
}},refreshUI:function(){this._refreshing=true;
var controlData=this.get_controlData();
if(!controlData){return;
}var currentView=this.get_currentMasterView();
this._includesChildLibraryItems=currentView.IncludeDescendantItems===null||currentView.IncludeDescendantItems===true;
if(currentView.ItemsParentId==Telerik.Sitefinity.getEmptyGuid()){this._allItemsRadio.click();
}else{this._libraryRadio.click();
this.get_selectedLibrary().innerText=this._selectedLibraryTitle;
jQuery(this.get_selectedLibrary()).show();
if(this.get_includesChildLibraryItemsLabel()){jQuery(this.get_includesChildLibraryItemsLabel()).toggle(this._includesChildLibraryItems);
}}this._refreshFilterUI();
if(this.get_sortingField()._get_listItemByValue(currentView.SortExpression).length==0){this.get_sortingField().set_value("custom");
}else{this.get_sortingField().set_value(currentView.SortExpression);
}if(this._haveLibraries==false){jQuery(this._selectLibraryButton).hide();
}this._refreshing=false;
},applyChanges:function(){var parent=this.get_parentDesigner();
var currentView=this._getCurrentView(parent);
if(this._libraryRadio.checked){if(this._selectedLibraryId){currentView.ItemsParentId=this._selectedLibraryId;
currentView.IncludeDescendantItems=this._includesChildLibraryItems;
}}else{currentView.ItemsParentId=Telerik.Sitefinity.getEmptyGuid();
}var sortExpression=this.get_sortingField().get_value();
if(sortExpression!="custom"){currentView.SortExpression=sortExpression;
}this._applyFilterChanges(currentView);
},get_currentViewName:function(){return this.get_controlData().MasterViewName;
},_setContentFilter:SelectorDesignerView$setContentFilter,_refreshFilterUI:SelectorDesignerView$refreshFilterUI,_applyFilterChanges:SelectorDesignerView$applyFilterChanges,_btnNarrowSelectionClick:function(){jQuery(this._narrowSelection).toggleClass("sfExpandedSection");
dialogBase.resizeToContent();
},get_parentDesigner:function(){return this._parentDesigner;
},set_parentDesigner:function(value){if(this._parentDesigner!=value){this._parentDesigner=value;
this.raisePropertyChanged("parentDesigner");
}},get_controlData:function(){return this.get_parentDesigner().get_propertyEditor().get_control();
},get_radioChoices:function(){if(!this._radioChoices){this._radioChoices=jQuery(this.get_element()).find(":radio[name$=ContentSelection]");
}return this._radioChoices;
},get_currentMasterViewName:function(){return(this._currentMasterViewName)?this._currentMasterViewName:this.get_controlData().MasterViewName;
},get_currentMasterView:function(){return this.get_controlData().ControlDefinition.Views[this.get_currentMasterViewName()];
},get_folderSelector:function(){return this._folderSelector;
},set_folderSelector:function(value){this._folderSelector=value;
},get_selectedLibrary:function(){return this._selectedLibrary;
},set_selectedLibrary:function(value){if(this._selectedLibrary!=value){this._selectedLibrary=value;
this.raisePropertyChanged("selectedLibrary");
}},get_allItemsRadio:function(){return this._allItemsRadio;
},set_allItemsRadio:function(value){if(this._allItemsRadio!=value){this._allItemsRadio=value;
this.raisePropertyChanged("allItemsRadio");
}},get_libraryRadio:function(){return this._libraryRadio;
},set_libraryRadio:function(value){if(this._libraryRadio!=value){this._libraryRadio=value;
this.raisePropertyChanged("libraryRadio");
}},get_uploadRadio:function(){return this._uploadRadio;
},set_uploadRadio:function(value){if(this._uploadRadio!=value){this._uploadRadio=value;
this.raisePropertyChanged("uploadRadio");
}},get_sortingField:function(){return this._sortingField;
},set_sortingField:function(value){this._sortingField=value;
},get_uploadButton:function(){return this._uploadButton;
},set_uploadButton:function(value){this._uploadButton=value;
},get_filterSelector:function(){return this._filterSelector;
},set_filterSelector:function(value){this._filterSelector=value;
},get_btnNarrowSelection:function(){return this._btnNarrowSelection;
},set_btnNarrowSelection:function(value){this._btnNarrowSelection=value;
},get_narrowSelection:function(){return this._narrowSelection;
},set_narrowSelection:function(value){this._narrowSelection=value;
},get_selectorTag:function(){return this._selectorTag;
},set_selectorTag:function(value){this._selectorTag=value;
},get_providersSelector:function(){return this._providersSelector;
},set_providersSelector:function(value){this._providersSelector=value;
},get_noContentSelectedLabel:function(){return this._noContentSelectedLabel;
},set_noContentSelectedLabel:function(value){this._noContentSelectedLabel=value;
},get_selectLibraryButtonWrapper:function(){return this._selectLibraryButtonWrapper;
},set_selectLibraryButtonWrapper:function(value){this._selectLibraryButtonWrapper=value;
},get_includesChildLibraryItemsLabel:function(){return this._includesChildLibraryItemsLabel;
},set_includesChildLibraryItemsLabel:function(value){this._includesChildLibraryItemsLabel=value;
}};
Telerik.Sitefinity.Modules.Libraries.Web.UI.Designers.MediaContentSelectorsDesignerView.registerClass("Telerik.Sitefinity.Modules.Libraries.Web.UI.Designers.MediaContentSelectorsDesignerView",Sys.UI.Control,Telerik.Sitefinity.Web.UI.ControlDesign.IDesignerViewControl);
