Type.registerNamespace("Telerik.Sitefinity.Modules.Comments.Web.UI.Frontend.Designer");
Telerik.Sitefinity.Modules.Comments.Web.UI.Frontend.Designer.CommentsWidgetDesigner=function(element){this._commentsTemplatesSelector=null;
this._commentsListViewTemplateSelector=null;
this._commentsSubmitFormTemplateSelectorControl=null;
this._commentsSubmitFormTemplateKeyName="ViewTemplateKey";
this._commentsListViewTemplateKeyName="ListViewTemplateKey";
Telerik.Sitefinity.Modules.Comments.Web.UI.Frontend.Designer.CommentsWidgetDesigner.initializeBase(this,[element]);
};
Telerik.Sitefinity.Modules.Comments.Web.UI.Frontend.Designer.CommentsWidgetDesigner.prototype={initialize:function(){Telerik.Sitefinity.Modules.Comments.Web.UI.Frontend.Designer.CommentsWidgetDesigner.callBaseMethod(this,"initialize");
},dispose:function(){Telerik.Sitefinity.Modules.Comments.Web.UI.Frontend.Designer.CommentsWidgetDesigner.callBaseMethod(this,"dispose");
},findElement:function(id){var result=jQuery(this.get_element()).find("#"+id).get(0);
return result;
},refreshUI:function(){var controlData=this._propertyEditor.get_control();
this.get_commentsTemplatesSelector().refreshUI();
this.get_commentsListViewTemplateSelector().refreshUI(this._commentsListViewTemplateKeyName);
this.get_commentsSubmitFormTemplateSelectorControl().refreshUI(this._commentsSubmitFormTemplateKeyName);
},applyChanges:function(){var controlData=this._propertyEditor.get_control();
this.get_commentsTemplatesSelector().applyChanges();
this.get_commentsListViewTemplateSelector().applyChanges(this._commentsListViewTemplateKeyName);
this.get_commentsSubmitFormTemplateSelectorControl().applyChanges(this._commentsSubmitFormTemplateKeyName);
},get_commentsTemplatesSelector:function(){return this._commentsTemplatesSelector;
},set_commentsTemplatesSelector:function(value){this._commentsTemplatesSelector=value;
},get_commentsListViewTemplateSelector:function(){return this._commentsListViewTemplateSelector;
},set_commentsListViewTemplateSelector:function(value){this._commentsListViewTemplateSelector=value;
},get_commentsSubmitFormTemplateSelectorControl:function(){return this._commentsSubmitFormTemplateSelectorControl;
},set_commentsSubmitFormTemplateSelectorControl:function(value){this._commentsSubmitFormTemplateSelectorControl=value;
},};
Telerik.Sitefinity.Modules.Comments.Web.UI.Frontend.Designer.CommentsWidgetDesigner.registerClass("Telerik.Sitefinity.Modules.Comments.Web.UI.Frontend.Designer.CommentsWidgetDesigner",Telerik.Sitefinity.Web.UI.ControlDesign.ControlDesignerBase);
