Type.registerNamespace("Telerik.Sitefinity.Modules.GenericContent.Web.UI");
Telerik.Sitefinity.Modules.GenericContent.Web.UI.ContentBlockDesignerBase=function(element){this._propertyEditor=null;
this._htmlEditor=null;
Telerik.Sitefinity.Modules.GenericContent.Web.UI.ContentBlockDesignerBase.initializeBase(this,[element]);
};
Telerik.Sitefinity.Modules.GenericContent.Web.UI.ContentBlockDesignerBase.prototype={initialize:function(){Telerik.Sitefinity.Modules.GenericContent.Web.UI.ContentBlockDesignerBase.callBaseMethod(this,"initialize");
},dispose:function(){Telerik.Sitefinity.Modules.GenericContent.Web.UI.ContentBlockDesignerBase.callBaseMethod(this,"dispose");
},applyChanges:function(){var editor=this._htmlEditor._editControl;
if(editor){editor.set_mode(1);
}this.get_propertyEditor().get_control().Html=this._htmlEditor.get_value();
},refreshUI:function(){var html=this.get_propertyEditor().get_control().Html;
if(html){this._htmlEditor.set_value(html);
}},get_propertyEditor:function(){return this._propertyEditor;
},set_propertyEditor:function(value){this._propertyEditor=value;
},get_htmlEditor:function(){return this._htmlEditor;
},set_htmlEditor:function(value){this._htmlEditor=value;
}};
Telerik.Sitefinity.Modules.GenericContent.Web.UI.ContentBlockDesignerBase.registerClass("Telerik.Sitefinity.Modules.GenericContent.Web.UI.ContentBlockDesignerBase",Telerik.Sitefinity.Web.UI.ControlDesign.ControlDesignerBase);
