Telerik.Sitefinity.Web.UI.ControlDesign.ContentViewDesignerBase=function(element){Telerik.Sitefinity.Web.UI.ControlDesign.ContentViewDesignerBase.initializeBase(this,[element]);
this._designerViewsMap=null;
this._menuTabStrip=null;
this._clientTabSelectedDelegate=null;
this._hiddenViews=[];
this._message=null;
};
Telerik.Sitefinity.Web.UI.ControlDesign.ContentViewDesignerBase.prototype={initialize:function(){Telerik.Sitefinity.Web.UI.ControlDesign.ContentViewDesignerBase.callBaseMethod(this,"initialize");
Sys.Application.add_load(Function.createDelegate(this,this._onLoad));
this._clientTabSelectedDelegate=Function.createDelegate(this,this._clientTabSelectedHandler);
this._menuTabStrip.add_tabSelected(this._clientTabSelectedDelegate);
},dispose:function(){Telerik.Sitefinity.Web.UI.ControlDesign.ContentViewDesignerBase.callBaseMethod(this,"dispose");
if(this._clientTabSelectedDelegate){this._menuTabStrip.remove_tabSelected(this._clientTabSelectedDelegate);
delete this._clientTabSelectedDelegate;
}},refreshUI:function(){if(this._designerViewsMap!=null){for(var i in this._designerViewsMap){if($find(this._designerViewsMap[i])!==null){$find(this._designerViewsMap[i]).refreshUI();
}}}},applyChanges:function(){if(this._designerViewsMap!=null){for(var i in this._designerViewsMap){if($find(this._designerViewsMap[i])!==null){$find(this._designerViewsMap[i]).applyChanges();
}}}},setFieldControlValueToControlData:function(fieldControl,controlData){var value=fieldControl.get_value();
var propertyPath=fieldControl.get_fieldName();
this.setValueToControlData(propertyPath,value);
},setValueToControlData:function(propertyPath,value,controlData){var res=this._setValueByPath(propertyPath,controlData,value);
if(!res){}},showDesignerOptions:function(){this.get_menuTabStrip().get_element().style.display="";
},hideDesignerOptions:function(){this.get_menuTabStrip().get_element().style.display="none";
},executeCommand:function(argument){},selectView:function(viewName){if(viewName){var tab=this.get_menuTabStrip().findTabByValue(viewName);
if(tab){tab.select();
this.set_saveButtonEnabled(true);
var view=$find(this._designerViewsMap[viewName]);
if(typeof view.notifyViewSelected==="function"){view.notifyViewSelected();
}}}},isViewSelected:function(view){var views=this.get_designerViewsMap();
return views[this.get_currentViewName()]==view.get_id();
},_onLoad:function(){if(this._designerViewsMap!=null){for(var i in this._designerViewsMap){if($find(this._designerViewsMap[i])!==null){$find(this._designerViewsMap[i]).set_parentDesigner(this);
}}}Telerik.Sitefinity.Web.UI.ControlDesign.ContentViewDesignerBase.callBaseMethod(this,"_onLoad");
this._hideTabsOfHiddenViews();
dialogBase.resizeToContent();
},_clientTabSelectedHandler:function(sender,args){var viewName=sender.get_selectedTab().get_value();
var designerView=$find(this._designerViewsMap[viewName]);
if(typeof designerView.notifyViewSelected==="function"){designerView.notifyViewSelected();
}this._processHiddenView(viewName);
dialogBase.resizeToContent();
},_processHiddenView:function(viewName){if(Array.indexOf(this.get_hiddenViews(),viewName)<0){this.showDesignerOptions();
}else{this.hideDesignerOptions();
}},_hideTabsOfHiddenViews:function(){var length=this._hiddenViews.length;
if(length>0){var menuTabStrip=this.get_menuTabStrip();
this._processHiddenView(menuTabStrip.get_selectedTab().get_value());
for(var i=0;
i<length;
i++){var tab=menuTabStrip.findTabByValue(this._hiddenViews[i]);
if(tab){tab.get_element().style.display="none";
}}}},get_designerViewsMap:function(){return this._designerViewsMap;
},set_designerViewsMap:function(value){this._designerViewsMap=value;
},get_menuTabStrip:function(){return this._menuTabStrip;
},set_menuTabStrip:function(value){this._menuTabStrip=value;
},get_hiddenViews:function(){return this._hiddenViews;
},set_hiddenViews:function(value){this._hiddenViews=value;
},get_currentViewName:function(){return this.get_menuTabStrip().get_selectedTab().get_value();
},set_saveButtonText:function(text){jQuery(this.get_saveButton()).find(".sfLinkBtnIn").text(text);
},set_saveButtonEnabled:function(state){jQuery(this.get_saveButton())[state?"removeClass":"addClass"]("sfDisabledLinkBtn");
},get_saveButton:function(){return this.get_propertyEditor().get_saveButton();
},get_message:function(){return this._message;
},set_message:function(value){this._message=value;
},_pathToChunks:function(path){path=path.replace(/\[/g,".");
path=path.replace(/\]/g,"");
path=path.replace(/\"|\'/g,"");
return path.split(".");
},_setValueByPath:function(path,obj,value){var pathChunks;
if(path.constructor!=Array){pathChunks=this._pathToChunks(path);
}else{pathChunks=path;
}var currentChunk=pathChunks[0];
var depth=pathChunks.length;
var ready=false;
for(var memberName in obj){if(memberName==currentChunk){if(depth==1){obj[memberName]=value;
ready=true;
}else{ready=this._setValueByPath(pathChunks.slice(1),obj[memberName],value);
}}if(ready){return true;
}}return false;
}};
Telerik.Sitefinity.Web.UI.ControlDesign.ContentViewDesignerBase.registerClass("Telerik.Sitefinity.Web.UI.ControlDesign.ContentViewDesignerBase",Telerik.Sitefinity.Web.UI.ControlDesign.ControlDesignerBase);
if(typeof(Sys)!=="undefined"){Sys.Application.notifyScriptLoaded();
}