Type._registerScript("DynamicContentSelectorsDesignerView.js",["ContentSelectorsDesignerView.js"]);
Type.registerNamespace("Telerik.Sitefinity.Web.UI.ControlDesign");
Telerik.Sitefinity.Web.UI.ControlDesign.DynamicContentSelectorsDesignerView=function(element){Telerik.Sitefinity.Web.UI.ControlDesign.DynamicContentSelectorsDesignerView.initializeBase(this,[element]);
this._mainFieldName=null;
this._contentViewDisplayMode=null;
this._dataItemId=null;
this._onLoadDelegate=null;
this._contentSelectorCultureFilter=null;
this._buttonSelectText=null;
this._buttonChangeText=null;
};
Telerik.Sitefinity.Web.UI.ControlDesign.DynamicContentSelectorsDesignerView.prototype={initialize:function(){Telerik.Sitefinity.Web.UI.ControlDesign.DynamicContentSelectorsDesignerView.callBaseMethod(this,"initialize");
this._onLoadDelegate=Function.createDelegate(this,this._onLoad);
Sys.Application.add_load(this._onLoadDelegate);
$(this).on("unload",function(e){jQuery.event.remove(this);
jQuery.removeData(this);
});
},dispose:function(){Telerik.Sitefinity.Web.UI.ControlDesign.DynamicContentSelectorsDesignerView.callBaseMethod(this,"dispose");
if(this._onLoadDelegate){Sys.Application.remove_load(this._onLoadDelegate);
delete this._onLoadDelegate;
}},applyChanges:function(){this.get_controlData().ContentViewDisplayMode=this._contentViewDisplayMode;
this.get_currentDetailView().DataItemId=this._dataItemId;
Telerik.Sitefinity.Web.UI.ControlDesign.DynamicContentSelectorsDesignerView.callBaseMethod(this,"applyChanges");
},_onLoad:function(){this._contentViewDisplayMode=this.get_controlData().ContentViewDisplayMode;
this._dataItemId=this.get_currentDetailView().DataItemId;
if(this._dataItemId===Telerik.Sitefinity.getEmptyGuid()){this._setSelectContentButtonText(this._buttonSelectText);
}else{this._setSelectContentButtonText(this._buttonChangeText);
}},_showContentSelector:function(){var contentSelector=this.get_contentSelector();
if(contentSelector){contentSelector.get_itemSelector()._selectorSearchBox.get_binderSearch()._multilingual=false;
if(this._contentSelectorCultureFilter){this.get_contentSelector().set_itemsFilter(this._contentSelectorCultureFilter);
}contentSelector.dataBind();
var dataItemId=this._dataItemId;
if(dataItemId){contentSelector.set_selectedKeys([dataItemId]);
}}this._dialog.dialog("open");
jQuery("body > form").hide();
dialogBase.resizeToContent();
},_selectContent:function(items){this._dialog.dialog("close");
jQuery("body > form").show();
dialogBase.resizeToContent();
if(items==null){return;
}var selectedItems=this.get_contentSelector().getSelectedItems();
if(selectedItems!=null){if(selectedItems.length>0){if(selectedItems[0].hasOwnProperty(this._mainFieldName)){if(selectedItems[0][this._mainFieldName].hasOwnProperty("Value")){this.get_selectedContentTitle().innerText=selectedItems[0][this._mainFieldName].Value;
}else{this.get_selectedContentTitle().innerText=selectedItems[0][this._mainFieldName];
}}this._dataItemId=selectedItems[0].Id;
this._contentViewDisplayMode="Detail";
jQuery(this.get_selectedContentTitle()).show();
this._setSelectContentButtonText(this._buttonChangeText);
}else{this._setSelectContentButtonText(this._buttonSelectText);
}}},_resetViewOnProvidersChanged:function(){Telerik.Sitefinity.Web.UI.ControlDesign.DynamicContentSelectorsDesignerView.callBaseMethod(this,"_resetViewOnProvidersChanged");
this._dataItemId=Telerik.Sitefinity.getEmptyGuid();
},_setContentFilter:function(sender){var radioID=sender.target.value;
var disabledFilter=true;
switch(radioID){case"contentSelect_AllItems":jQuery(this.get_element()).find("#selectorPanel").hide();
if(!this._refreshing){this._contentViewDisplayMode="Automatic";
}break;
case"contentSelect_OneItem":jQuery(this.get_element()).find("#selectorPanel").show();
if(!this._refreshing){this._contentViewDisplayMode="Detail";
}break;
case"contentSelect_SimpleFilter":jQuery(this.get_element()).find("#selectorPanel").hide();
disabledFilter=false;
if(!this._refreshing){this._contentViewDisplayMode="Automatic";
}break;
case"contentSelect_AdvancedFilter":break;
}this._filterSelector.set_disabled(disabledFilter);
dialogBase.resizeToContent();
},_setSelectContentButtonText:function(value){$(this._element).find("#"+this._selectContentButton).text(value);
},};
Telerik.Sitefinity.Web.UI.ControlDesign.DynamicContentSelectorsDesignerView.registerClass("Telerik.Sitefinity.Web.UI.ControlDesign.DynamicContentSelectorsDesignerView",Telerik.Sitefinity.Web.UI.ControlDesign.ContentSelectorsDesignerView);
if(typeof(Sys)!=="undefined"){Sys.Application.notifyScriptLoaded();
}