Type.registerNamespace("Telerik.Sitefinity.Web.UI.Fields.Designers.Views");
Telerik.Sitefinity.Web.UI.Fields.Designers.Views.ImageFieldLimitationsView=function(element){Telerik.Sitefinity.Web.UI.Fields.Designers.Views.ImageFieldLimitationsView.initializeBase(this,[element]);
this._widthTextField=null;
this._heightTextField=null;
this._rangeViolationMessageField=null;
};
Telerik.Sitefinity.Web.UI.Fields.Designers.Views.ImageFieldLimitationsView.prototype={initialize:function(){Telerik.Sitefinity.Web.UI.Fields.Designers.Views.ImageFieldLimitationsView.callBaseMethod(this,"initialize");
},dispose:function(){Telerik.Sitefinity.Web.UI.Fields.Designers.Views.ImageFieldLimitationsView.callBaseMethod(this,"dispose");
},refreshUI:function(){var controlData=this.get_controlData();
if(controlData&&controlData.MaxWidth){this._widthTextField.set_value(controlData.MaxWidth);
}else{this._widthTextField.reset();
}if(controlData&&controlData.MaxHeight){this._heightTextField.set_value(controlData.MaxHeight);
}else{this._heightTextField.reset();
}},applyChanges:function(){var controlData=this.get_controlData();
controlData.MaxWidth=this._widthTextField.get_value()?this._widthTextField.get_value():0;
controlData.MaxHeight=this._heightTextField.get_value()?this._heightTextField.get_value():0;
},get_controlData:function(){return this.get_parentDesigner().get_propertyEditor().get_control();
},get_parentDesigner:function(){return this._parentDesigner;
},set_parentDesigner:function(value){this._parentDesigner=value;
},get_propertyEditor:function(){if(this.get_parentDesigner()){return this.get_parentDesigner().get_propertyEditor();
}return null;
},get_widthTextField:function(){return this._widthTextField;
},set_widthTextField:function(value){this._widthTextField=value;
},get_heightTextField:function(){return this._heightTextField;
},set_heightTextField:function(value){this._heightTextField=value;
}};
Telerik.Sitefinity.Web.UI.Fields.Designers.Views.ImageFieldLimitationsView.registerClass("Telerik.Sitefinity.Web.UI.Fields.Designers.Views.ImageFieldLimitationsView",Sys.UI.Control,Telerik.Sitefinity.Web.UI.ControlDesign.IDesignerViewControl);
