Type.registerNamespace("Telerik.Sitefinity.Web.UI");
Telerik.Sitefinity.Web.UI.DateRangeSelectorResultView=function(element){this._selector=null;
this._chooseButtonTextControlId=null;
this._selectLabel=null;
this._changeLabel=null;
Telerik.Sitefinity.Web.UI.DateRangeSelectorResultView.initializeBase(this,[element]);
};
Telerik.Sitefinity.Web.UI.DateRangeSelectorResultView.prototype={initialize:function(){Telerik.Sitefinity.Web.UI.DateRangeSelectorResultView.callBaseMethod(this,"initialize");
},dispose:function(){Telerik.Sitefinity.Web.UI.DateRangeSelectorResultView.callBaseMethod(this,"dispose");
},refreshUI:function(){var value=this._selector.get_value();
if(value){this._binder.BindCollection({Items:[value]});
jQuery("#"+this._chooseButtonTextControlId).html(this._changeLabel);
}else{this._binder.ClearTarget();
jQuery("#"+this._chooseButtonTextControlId).html(this._selectLabel);
}},validate:function(){return this._selector.validate();
},get_selectedItems:function(){return this.get_selectedValues();
},set_selectedItems:function(value){this.set_selectedValues(value);
},get_selectedValues:function(){var val=this._selector.get_value();
if(val){return[val];
}else{return[];
}},set_selectedValues:function(value){if(value&&value.length>0){this._selector.set_value(value[0]);
}else{this._selector.set_value(null);
}this.refreshUI();
},onLoad:function(){},doneClicked:function(){this.refreshUI();
},cancelClicked:function(){}};
Telerik.Sitefinity.Web.UI.DateRangeSelectorResultView.registerClass("Telerik.Sitefinity.Web.UI.DateRangeSelectorResultView",Telerik.Sitefinity.Web.UI.SelectorResultView);
