Type.registerNamespace("Telerik");
Type.registerNamespace("Telerik.Sitefinity");
Type.registerNamespace("Telerik.Sitefinity.Web");
Type.registerNamespace("Telerik.Sitefinity.Web.UI");
Telerik.Sitefinity.Web.UI.RadBreadCrumb=function(element){Telerik.Sitefinity.Web.UI.RadBreadCrumb.initializeBase(this,[element]);
this._list=[];
};
Telerik.Sitefinity.Web.UI.RadBreadCrumb.prototype={get_clientStateFieldID:function(){},set_clientStateFieldID:function(){},add_click:function(handler){this.get_events().addHandler("click",handler);
},remove_click:function(handler){this.get_events().removeHandler("click",handler);
},_raiseClick:function(args){var h=this.get_events().getHandler("click");
if(h){h(this,args);
}},initialize:function(){Telerik.Sitefinity.Web.UI.RadBreadCrumb.callBaseMethod(this,"initialize");
this._registerMouseHandlers(true);
},_registerMouseHandlers:function(attachEvent){var targetElement=this.get_element();
if(true==attachEvent){var handlers={click:this._onMouseClick};
$addHandlers(targetElement,handlers,this);
}else{$clearHandlers(targetElement);
}},dispose:function(){this._clear();
this._registerMouseHandlers(false);
Telerik.Sitefinity.Web.UI.RadBreadCrumb.callBaseMethod(this,"dispose");
},_onMouseClick:function(e){var index=this._getClickedIndex(e);
var obj=this._list[index];
this._raiseClick(obj);
return $telerik.cancelRawEvent(e);
},_getClickedIndex:function(e){var target=e.target;
if(!target||target.tagName!="A"){return -1;
}var links=this.get_element().getElementsByTagName("A");
for(var i=0;
i<links.length;
i++){if(links[i]==target){return i;
}}return -1;
},_clear:function(){this.get_element().innerHTML="&nbsp;";
this._list=[];
},_addBreadcrumb:function(text,isLast){var parent=this.get_element();
var domLink=null;
if(isLast){domLink=document.createElement("SPAN");
}else{domLink=document.createElement("A");
domLink.href="javascript:void(0);";
}domLink.innerHTML=text;
parent.appendChild(domLink);
if(!isLast){var arrow=document.createElement("SPAN");
arrow.innerHTML="&nbsp;> ";
arrow.className="bcArrow";
parent.appendChild(arrow);
}},set_list:function(array){this._clear();
this._list=array;
for(var i=0;
i<array.length;
i++){var item=array[i];
this._addBreadcrumb(item.text,i>=array.length-1);
}}};
Telerik.Sitefinity.Web.UI.RadBreadCrumb.registerClass("Telerik.Sitefinity.Web.UI.RadBreadCrumb",Sys.UI.Control);
