function get_encodeWcfMap(){var encodeMap=new Array();
encodeMap["."]="__dot__";
encodeMap["]"]="__rsb__";
encodeMap["["]="__lsb__";
encodeMap["}"]="__rcb__";
encodeMap["{"]="__lcb__";
encodeMap["`"]="__gr__";
encodeMap[","]="__cm__";
encodeMap[" "]="__sp__";
encodeMap["="]="__eq__";
encodeMap["#"]="__pd__";
encodeMap["?"]="__qm__";
encodeMap[":"]="__cl__";
encodeMap["%"]="__pct__";
return encodeMap;
}function get_decodeWcfMap(){var encodeMap=get_encodeWcfMap();
var decodeMap=new Array();
for(var codeEntry in encodeMap){decodeMap[encodeMap[codeEntry]]=codeEntry;
}return decodeMap;
}function encodeWcfString(wcfString){if(typeof(wcfString)==typeof("")&&wcfString!=null&&wcfString.length>0){var encoded=wcfString;
var encodeMap=get_encodeWcfMap();
for(var codeSymbol in encodeMap){encoded=encoded.replace(codeSymbol,encodeMap[codeSymbol],"g");
}return encoded;
}else{return"";
}}function decodeWcfString(wcfString){if(typeof(wcfString)==typeof("")&&wcfString!=null&&wcfString.length>0){var decoded=wcfString;
var decodeMap=get_decodeWcfMap();
for(var decodeSymbol in decodeMap){decoded=decoded.replace(decodeSymbol,decodeMap[decodeSymbol],"g");
}return decoded;
}else{return"";
}}