Type._registerScript("CssEditorDesignerView.js",["IDesignerViewControl.js"]);
Type.registerNamespace("Telerik.Sitefinity.Web.UI.PublicControls.Designers.Views");
Telerik.Sitefinity.Web.UI.PublicControls.Designers.Views.CssEditorDesignerView=function(element){Telerik.Sitefinity.Web.UI.PublicControls.Designers.Views.CssEditorDesignerView.initializeBase(this,[element]);
this._parentDesigner=null;
this._customCssCodeTextField=null;
this._mediaChoiceField=null;
this._mediaTypesChoiceField=null;
this._mediaChoiceFieldChangedDelegate=null;
this._mediaTypesMap={};
this._codeMirror=null;
};
Telerik.Sitefinity.Web.UI.PublicControls.Designers.Views.CssEditorDesignerView.prototype={initialize:function(){Telerik.Sitefinity.Web.UI.PublicControls.Designers.Views.CssEditorDesignerView.callBaseMethod(this,"initialize");
this._mediaChoiceFieldChangedDelegate=Function.createDelegate(this,this._mediaChangeHandler);
this._mediaChoiceField.add_valueChanged(this._mediaChoiceFieldChangedDelegate);
this._codeMirror=CodeMirror.fromTextArea(this._customCssCodeTextField.get_textElement(),{mode:"css",lineNumbers:true,matchBrackets:true,tabMode:"classic"});
},dispose:function(){Telerik.Sitefinity.Web.UI.PublicControls.Designers.Views.CssEditorDesignerView.callBaseMethod(this,"dispose");
if(this._mediaChoiceFieldChangedDelegate){if(this._mediaChoiceField){this._mediaChoiceField.remove_valueChanged(this._mediaChoiceFieldChangedDelegate);
}delete this._mediaChoiceFieldChangedDelegate;
}},refreshUI:function(){var controlData=this.get_controlData();
if(controlData.CustomCssCode){var parentDesigner=this.get_parentDesigner();
var tab=parentDesigner.get_menuTabStrip().findTabByValue("CssEditorDesignerView");
tab.select();
this.get_CodeMirror().setValue(controlData.CustomCssCode);
if(controlData.MediaType=="all"){this.get_mediaChoiceField().set_value("all");
}else{this.get_mediaChoiceField().set_value("selectMediaTypes");
var selectedTypes=[];
var typesArray=controlData.MediaType.split(",");
for(var i=0,length=typesArray.length;
i<length;
i++){var enumValue=this._mediaTypesMap[typesArray[i].trim()];
if(enumValue){selectedTypes.push(enumValue);
}}this.get_mediaTypesChoiceField().set_value(selectedTypes);
}}},applyChanges:function(){var parentDesigner=this.get_parentDesigner();
var selectedTab=parentDesigner.get_menuTabStrip().get_selectedTab();
var tabValue=selectedTab.get_value();
if(tabValue=="CssEditorDesignerView"){var controlData=this.get_controlData();
controlData.CustomCssCode=this.get_CodeMirror().getValue();
controlData.Url="";
if(this.get_mediaChoiceField().get_value()=="all"){controlData.MediaType=1;
}else{var mediaType=this.get_mediaTypesChoiceField().get_value();
if(Array.prototype.isPrototypeOf(mediaType)){var mask=0;
for(var i=0,length=mediaType.length;
i<length;
i++){var flag=parseInt(mediaType[i]);
mask=mask|flag;
}controlData.MediaType=mask;
}else{controlData.MediaType=mediaType;
}}}},get_controlData:function(){return this.get_parentDesigner().get_propertyEditor().get_control();
},_mediaChangeHandler:function(sender,args){var value=sender.get_value();
if(value=="all"){jQuery(this._mediaTypesChoiceField.get_element()).hide();
}else{jQuery(this._mediaTypesChoiceField.get_element()).show();
}dialogBase.resizeToContent();
},get_parentDesigner:function(){return this._parentDesigner;
},set_parentDesigner:function(value){this._parentDesigner=value;
},get_propertyEditor:function(){if(this.get_parentDesigner()){return this.get_parentDesigner().get_propertyEditor();
}return null;
},get_customCssCodeTextField:function(){return this._customCssCodeTextField;
},set_customCssCodeTextField:function(value){this._customCssCodeTextField=value;
},get_mediaChoiceField:function(){return this._mediaChoiceField;
},set_mediaChoiceField:function(value){this._mediaChoiceField=value;
},get_mediaTypesChoiceField:function(){return this._mediaTypesChoiceField;
},set_mediaTypesChoiceField:function(value){this._mediaTypesChoiceField=value;
},get_CodeMirror:function(){return this._codeMirror;
},set_CodeMirror:function(value){this._codeMirror=value;
}};
Telerik.Sitefinity.Web.UI.PublicControls.Designers.Views.CssEditorDesignerView.registerClass("Telerik.Sitefinity.Web.UI.PublicControls.Designers.Views.CssEditorDesignerView",Sys.UI.Control,Telerik.Sitefinity.Web.UI.ControlDesign.IDesignerViewControl);
if(typeof(Sys)!=="undefined"){Sys.Application.notifyScriptLoaded();
}