Type.registerNamespace("Telerik.Sitefinity.Modules.Forms.Web.UI.Designers.Views");
Telerik.Sitefinity.Modules.Forms.Web.UI.Designers.Views.FormParagraphTextBoxLimitationsView=function(element){Telerik.Sitefinity.Modules.Forms.Web.UI.Designers.Views.FormParagraphTextBoxLimitationsView.initializeBase(this,[element]);
};
Telerik.Sitefinity.Modules.Forms.Web.UI.Designers.Views.FormParagraphTextBoxLimitationsView.prototype={initialize:function(){Telerik.Sitefinity.Modules.Forms.Web.UI.Designers.Views.FormParagraphTextBoxLimitationsView.callBaseMethod(this,"initialize");
},dispose:function(){Telerik.Sitefinity.Modules.Forms.Web.UI.Designers.Views.FormParagraphTextBoxLimitationsView.callBaseMethod(this,"dispose");
},refreshUI:function(){var controlData=this.get_controlData();
if(controlData.ValidatorDefinition&&controlData.ValidatorDefinition.MinLength){this._minRangeField.set_value(controlData.ValidatorDefinition.MinLength);
}else{this._minRangeField.set_value("0");
}if(controlData.ValidatorDefinition&&controlData.ValidatorDefinition.MaxLength){this._maxRangeField.set_value(controlData.ValidatorDefinition.MaxLength);
}else{this._maxRangeField.reset();
}if(controlData.ValidatorDefinition.MaxLengthViolationMessage){this._rangeViolationMessageField.set_value(controlData.ValidatorDefinition.MaxLengthViolationMessage);
}},applyChanges:function(){var controlData=this.get_controlData();
controlData.ValidatorDefinition.MinLength=this._minRangeField.get_value()?this._minRangeField.get_value():0;
controlData.ValidatorDefinition.MaxLength=this._maxRangeField.get_value()?this._maxRangeField.get_value():0;
if(this._rangeViolationMessageField){controlData.ValidatorDefinition.MaxLengthViolationMessage=this._rangeViolationMessageField.get_value();
controlData.ValidatorDefinition.MinLengthViolationMessage=this._rangeViolationMessageField.get_value();
}},get_controlData:function(){return this.get_parentDesigner().get_propertyEditor().get_control();
},get_parentDesigner:function(){return this._parentDesigner;
},set_parentDesigner:function(value){this._parentDesigner=value;
},get_propertyEditor:function(){if(this.get_parentDesigner()){return this.get_parentDesigner().get_propertyEditor();
}return null;
},get_minRangeField:function(){return this._minRangeField;
},set_minRangeField:function(value){this._minRangeField=value;
},get_maxRangeField:function(){return this._maxRangeField;
},set_maxRangeField:function(value){this._maxRangeField=value;
},get_rangeViolationMessageField:function(){return this._rangeViolationMessageField;
},set_rangeViolationMessageField:function(value){this._rangeViolationMessageField=value;
}};
Telerik.Sitefinity.Modules.Forms.Web.UI.Designers.Views.FormParagraphTextBoxLimitationsView.registerClass("Telerik.Sitefinity.Modules.Forms.Web.UI.Designers.Views.FormParagraphTextBoxLimitationsView",Sys.UI.Control,Telerik.Sitefinity.Web.UI.ControlDesign.IDesignerViewControl);
