Type.registerNamespace("Telerik.Sitefinity.Modules.Forms.Web.UI.Fields");
Telerik.Sitefinity.Modules.Forms.Web.UI.Fields.FormCheckboxes=function(element){Telerik.Sitefinity.Modules.Forms.Web.UI.Fields.FormCheckboxes.initializeBase(this,[element]);
};
Telerik.Sitefinity.Modules.Forms.Web.UI.Fields.FormCheckboxes.prototype={initialize:function(){Telerik.Sitefinity.Modules.Forms.Web.UI.Fields.FormCheckboxes.callBaseMethod(this,"initialize");
},dispose:function(){Telerik.Sitefinity.Modules.Forms.Web.UI.Fields.FormCheckboxes.callBaseMethod(this,"dispose");
},_get_selectedItemsValues:function(){var result="";
var tempStringArray=[];
var selected=this._get_selectedListItemsElements();
if(selected&&selected.length>0){for(var i=0,length=selected.length;
i<length;
i++){tempStringArray.push(jQuery(selected[i]).attr("value"));
}result=tempStringArray.join(",");
}return result;
},_get_listItemByValue:function(value){var selector=this._get_listItemSelector();
if(value.indexOf(",")!=-1){var values=value.split(",");
var valuesLength=values.length;
while(valuesLength--){selector+="[value='"+this._cssEscape(values[valuesLength])+"']";
if(valuesLength>0){selector+=",";
}}}else{selector+="[value='"+this._cssEscape(value)+"']";
}return jQuery(this._choiceElement).find(selector);
},_cssEscape:function(value){var result="";
if(window.CSS&&window.CSS.escape){result=CSS.escape(value);
}else{if(arguments.length==0){throw new TypeError("`CSS.escape` requires an argument.");
}var string=String(value);
var length=string.length;
var index=-1;
var codeUnit;
var firstCodeUnit=string.charCodeAt(0);
while(++index<length){codeUnit=string.charCodeAt(index);
if(codeUnit==0){result+="\uFFFD";
continue;
}if((codeUnit>=1&&codeUnit<=31)||codeUnit==127||(index==0&&codeUnit>=48&&codeUnit<=57)||(index==1&&codeUnit>=48&&codeUnit<=57&&firstCodeUnit==45)){result+="\\"+codeUnit.toString(16)+" ";
continue;
}if(index==0&&length==1&&codeUnit==45){result+="\\"+string.charAt(index);
continue;
}if(codeUnit>=128||codeUnit==45||codeUnit==95||codeUnit>=48&&codeUnit<=57||codeUnit>=65&&codeUnit<=90||codeUnit>=97&&codeUnit<=122){result+=string.charAt(index);
continue;
}result+="\\"+string.charAt(index);
}}return result;
}};
Telerik.Sitefinity.Modules.Forms.Web.UI.Fields.FormCheckboxes.registerClass("Telerik.Sitefinity.Modules.Forms.Web.UI.Fields.FormCheckboxes",Telerik.Sitefinity.Web.UI.Fields.ChoiceField);
