Type.registerNamespace("Telerik.Sitefinity.Modules.Forms.Web.UI.Designers.Views");
Telerik.Sitefinity.Modules.Forms.Web.UI.Designers.Views.FormFileUploadAppearanceView=function(element){Telerik.Sitefinity.Modules.Forms.Web.UI.Designers.Views.FormFileUploadAppearanceView.initializeBase(this,[element]);
this._cssClassTextField=null;
};
Telerik.Sitefinity.Modules.Forms.Web.UI.Designers.Views.FormFileUploadAppearanceView.prototype={initialize:function(){Telerik.Sitefinity.Modules.Forms.Web.UI.Designers.Views.FormFileUploadAppearanceView.callBaseMethod(this,"initialize");
},dispose:function(){Telerik.Sitefinity.Modules.Forms.Web.UI.Designers.Views.FormFileUploadAppearanceView.callBaseMethod(this,"dispose");
},refreshUI:function(){var controlData=this.get_controlData();
this._cssClassTextField.set_value(controlData.CssClass);
},applyChanges:function(){var controlData=this.get_controlData();
controlData.CssClass=this._cssClassTextField.get_value();
},get_controlData:function(){return this.get_parentDesigner().get_propertyEditor().get_control();
},get_parentDesigner:function(){return this._parentDesigner;
},set_parentDesigner:function(value){this._parentDesigner=value;
},get_propertyEditor:function(){if(this.get_parentDesigner()){return this.get_parentDesigner().get_propertyEditor();
}return null;
},get_cssClassTextField:function(){return this._cssClassTextField;
},set_cssClassTextField:function(value){this._cssClassTextField=value;
}};
Telerik.Sitefinity.Modules.Forms.Web.UI.Designers.Views.FormFileUploadAppearanceView.registerClass("Telerik.Sitefinity.Modules.Forms.Web.UI.Designers.Views.FormFileUploadAppearanceView",Sys.UI.Control,Telerik.Sitefinity.Web.UI.ControlDesign.IDesignerViewControl);
