Type.registerNamespace("Telerik.Sitefinity.Modules.Forms.Web.UI.Designers.Views");
Telerik.Sitefinity.Modules.Forms.Web.UI.Designers.Views.FormChoiceFieldColumnsAppearanceView=function(element){Telerik.Sitefinity.Modules.Forms.Web.UI.Designers.Views.FormChoiceFieldColumnsAppearanceView.initializeBase(this,[element]);
this._columnsModeChoiceField=null;
this._cssClassTextField=null;
};
Telerik.Sitefinity.Modules.Forms.Web.UI.Designers.Views.FormChoiceFieldColumnsAppearanceView.prototype={initialize:function(){Telerik.Sitefinity.Modules.Forms.Web.UI.Designers.Views.FormChoiceFieldColumnsAppearanceView.callBaseMethod(this,"initialize");
},dispose:function(){Telerik.Sitefinity.Modules.Forms.Web.UI.Designers.Views.FormChoiceFieldColumnsAppearanceView.callBaseMethod(this,"dispose");
},refreshUI:function(){var controlData=this.get_controlData();
this._cssClassTextField.set_value(controlData.CssClass);
if(this._columnsModeChoiceField){this._columnsModeChoiceField.set_value(controlData.FormControlColumnsMode);
}},applyChanges:function(){var controlData=this.get_controlData();
controlData.CssClass=this._cssClassTextField.get_value();
if(this._columnsModeChoiceField){controlData.FormControlColumnsMode=this._columnsModeChoiceField.get_value();
}},get_controlData:function(){return this.get_parentDesigner().get_propertyEditor().get_control();
},get_parentDesigner:function(){return this._parentDesigner;
},set_parentDesigner:function(value){this._parentDesigner=value;
},get_propertyEditor:function(){if(this.get_parentDesigner()){return this.get_parentDesigner().get_propertyEditor();
}return null;
},get_columnsModeChoiceField:function(){return this._columnsModeChoiceField;
},set_columnsModeChoiceField:function(value){this._columnsModeChoiceField=value;
},get_cssClassTextField:function(){return this._cssClassTextField;
},set_cssClassTextField:function(value){this._cssClassTextField=value;
}};
Telerik.Sitefinity.Modules.Forms.Web.UI.Designers.Views.FormChoiceFieldColumnsAppearanceView.registerClass("Telerik.Sitefinity.Modules.Forms.Web.UI.Designers.Views.FormChoiceFieldColumnsAppearanceView",Sys.UI.Control,Telerik.Sitefinity.Web.UI.ControlDesign.IDesignerViewControl);
