Type.registerNamespace("Telerik.Sitefinity.Modules.Forms.Web.UI.Designers.Views");
Telerik.Sitefinity.Modules.Forms.Web.UI.Designers.Views.FormTextBoxLimitationsView=function(element){Telerik.Sitefinity.Modules.Forms.Web.UI.Designers.Views.FormTextBoxLimitationsView.initializeBase(this,[element]);
this._minRangeField=null;
this._maxRangeField=null;
this._rangeViolationMessageField=null;
this._recommendedCharectersField=null;
};
Telerik.Sitefinity.Modules.Forms.Web.UI.Designers.Views.FormTextBoxLimitationsView.prototype={initialize:function(){Telerik.Sitefinity.Modules.Forms.Web.UI.Designers.Views.FormTextBoxLimitationsView.callBaseMethod(this,"initialize");
},dispose:function(){Telerik.Sitefinity.Modules.Forms.Web.UI.Designers.Views.FormTextBoxLimitationsView.callBaseMethod(this,"dispose");
},refreshUI:function(){var controlData=this.get_controlData();
if(controlData.ValidatorDefinition&&controlData.ValidatorDefinition.MinLength){this._minRangeField.set_value(controlData.ValidatorDefinition.MinLength);
}else{this._minRangeField.set_value("0");
}if(controlData.ValidatorDefinition&&controlData.ValidatorDefinition.MaxLength){this._maxRangeField.set_value(controlData.ValidatorDefinition.MaxLength);
}else{this._maxRangeField.reset();
}if(controlData.ValidatorDefinition.MaxLengthViolationMessage){this._rangeViolationMessageField.set_value(controlData.ValidatorDefinition.MaxLengthViolationMessage);
}if(controlData.ValidatorDefinition.RecommendedCharactersCount){this._recommendedCharectersField.set_value(controlData.ValidatorDefinition.RecommendedCharactersCount);
}else{this._recommendedCharectersField.reset();
}if(controlData.FieldName==="MetaTitle"||controlData.FieldName==="MetaDescription"||controlData.FieldName==="OpenGraphTitle"||controlData.FieldName==="OpenGraphDescription"){jQuery(this._rangeViolationMessageField.get_element()).hide();
}else{jQuery("#recommendedCharectersFieldWrapper").hide();
}},applyChanges:function(){var controlData=this.get_controlData();
controlData.ValidatorDefinition.MinLength=this._minRangeField.get_value()?this._minRangeField.get_value():0;
controlData.ValidatorDefinition.MaxLength=this._maxRangeField.get_value()?this._maxRangeField.get_value():0;
controlData.ValidatorDefinition.RecommendedCharactersCount=this._recommendedCharectersField.get_value()?this._recommendedCharectersField.get_value():0;
if(this._rangeViolationMessageField){controlData.ValidatorDefinition.MaxLengthViolationMessage=this._rangeViolationMessageField.get_value();
controlData.ValidatorDefinition.MinLengthViolationMessage=this._rangeViolationMessageField.get_value();
}},get_controlData:function(){return this.get_parentDesigner().get_propertyEditor().get_control();
},get_parentDesigner:function(){return this._parentDesigner;
},set_parentDesigner:function(value){this._parentDesigner=value;
},get_propertyEditor:function(){if(this.get_parentDesigner()){return this.get_parentDesigner().get_propertyEditor();
}return null;
},get_minRangeField:function(){return this._minRangeField;
},set_minRangeField:function(value){this._minRangeField=value;
},get_maxRangeField:function(){return this._maxRangeField;
},set_maxRangeField:function(value){this._maxRangeField=value;
},get_recommendedCharectersField:function(){return this._recommendedCharectersField;
},set_recommendedCharectersField:function(value){this._recommendedCharectersField=value;
},get_rangeViolationMessageField:function(){return this._rangeViolationMessageField;
},set_rangeViolationMessageField:function(value){this._rangeViolationMessageField=value;
}};
Telerik.Sitefinity.Modules.Forms.Web.UI.Designers.Views.FormTextBoxLimitationsView.registerClass("Telerik.Sitefinity.Modules.Forms.Web.UI.Designers.Views.FormTextBoxLimitationsView",Sys.UI.Control,Telerik.Sitefinity.Web.UI.ControlDesign.IDesignerViewControl);
