Type.registerNamespace("Telerik.Sitefinity.Web.UI.Fields");
Telerik.Sitefinity.Web.UI.Fields.Choice=function(){this._text=null;
this._value=null;
this._description=null;
this._enabled=null;
Telerik.Sitefinity.Web.UI.Fields.Choice.initializeBase(this);
};
Telerik.Sitefinity.Web.UI.Fields.Choice.prototype={initialize:function(){Telerik.Sitefinity.Web.UI.Fields.Choice.callBaseMethod(this,"initialize");
},dispose:function(){Telerik.Sitefinity.Web.UI.Fields.Choice.callBaseMethod(this,"dispose");
},get_text:function(){return this._text;
},set_text:function(value){this._text=value;
},get_value:function(){return this._value;
},set_value:function(value){this._value=value;
},get_description:function(){return this._description;
},set_description:function(value){this._description=value;
},get_enabled:function(){return this._enabled;
},set_enabled:function(value){this._enabled=value;
}};
Telerik.Sitefinity.Web.UI.Fields.Choice.registerClass("Telerik.Sitefinity.Web.UI.Fields.Choice",Sys.Component);
