Type.registerNamespace("Telerik.Sitefinity.Web.UI.Fields");
Telerik.Sitefinity.Web.UI.Fields.FormFieldValidationEventArgs=function(fieldControl,validationGroup){this._fieldControl=fieldControl;
this._validated=false;
this._isValid=true;
this._validationGroup=validationGroup;
Telerik.Sitefinity.Web.UI.Fields.FormFieldValidationEventArgs.initializeBase(this);
};
Telerik.Sitefinity.Web.UI.Fields.FormFieldValidationEventArgs.prototype={initialize:function(){Telerik.Sitefinity.Web.UI.Fields.FormFieldValidationEventArgs.callBaseMethod(this,"initialize");
},dispose:function(){Telerik.Sitefinity.Web.UI.Fields.FormFieldValidationEventArgs.callBaseMethod(this,"dispose");
},get_fieldControl:function(){return this._fieldControl;
},set_fieldControl:function(value){this._fieldControl=value;
},get_isValid:function(){return this._isValid;
},set_isValid:function(value){this._isValid=value;
},get_validated:function(){return this._validated;
},set_validated:function(value){this._validated=value;
},get_validationGroup:function(){return this._validationGroup;
},set_validationGroup:function(value){this._validationGroup=value;
}};
Telerik.Sitefinity.Web.UI.Fields.FormFieldValidationEventArgs.registerClass("Telerik.Sitefinity.Web.UI.Fields.FormFieldValidationEventArgs",Sys.EventArgs);
Telerik.Sitefinity.Web.UI.Fields.ValidationCompletedEventArgs=function(violationMessages,validationGroup,validationResult){Telerik.Sitefinity.Web.UI.Fields.ValidationCompletedEventArgs.initializeBase(this);
this._validationGroup=validationGroup;
this._violationMessages=violationMessages;
this._validationResult=validationResult;
};
Telerik.Sitefinity.Web.UI.Fields.ValidationCompletedEventArgs.prototype={initialize:function(){Telerik.Sitefinity.Web.UI.Fields.ValidationCompletedEventArgs.callBaseMethod(this,"initialize");
},dispose:function(){Telerik.Sitefinity.Web.UI.Fields.ValidationCompletedEventArgs.callBaseMethod(this,"dispose");
},get_validationGroup:function(){return this._validationGroup;
},set_validationGroup:function(value){this._validationGroup=value;
},get_violationMessages:function(){return this._violationMessages;
},set_violationMessages:function(value){this._violationMessages=value;
},get_validationResult:function(){return this._validationResult;
}};
Telerik.Sitefinity.Web.UI.Fields.ValidationCompletedEventArgs.registerClass("Telerik.Sitefinity.Web.UI.Fields.ValidationCompletedEventArgs",Sys.EventArgs);
