Type.registerNamespace("Telerik.Sitefinity.Web.UI.Fields");
Telerik.Sitefinity.Web.UI.Fields.StatusField=function(element){this._element=element;
Telerik.Sitefinity.Web.UI.Fields.StatusField.initializeBase(this,[element]);
this._expirationDateComponent=null;
this._publicationDateComponent=null;
this._statusChoiseComponent=null;
this._choiceDescriptions=null;
this._readModeLabel=null;
this._messageLabel=null;
this._datesPanel=null;
this._onLoadDelegate=null;
this._onChoiceChangeDelegate=null;
};
Telerik.Sitefinity.Web.UI.Fields.StatusField.prototype={initialize:function(){Telerik.Sitefinity.Web.UI.Fields.StatusField.callBaseMethod(this,"initialize");
if(this.get_displayMode()==Telerik.Sitefinity.Web.UI.Fields.FieldDisplayMode.Write){this._onLoadDelegate=Function.createDelegate(this,this._on_load);
Sys.Application.add_load(this._onLoadDelegate);
this._onChoiceChangeDelegate=Function.createDelegate(this,this._on_choiceChange);
}else{}},dispose:function(){Telerik.Sitefinity.Web.UI.Fields.StatusField.callBaseMethod(this,"dispose");
},add_statusChanged:function(delegate){this.get_events().addHandler("statusChanged",delegate);
},remove_statusChanged:function(delegate){this.get_events().removeHandler("statusChanged",delegate);
},reset:function(){},_statusChangedHandler:function(){var h=this.get_events().getHandler("statusChanged");
if(h){h(this,Sys.EventArgs.Empty);
}return Sys.EventArgs.Empty;
},_on_load:function(){this._statusChoiseComponent.add_valueChanged(this._onChoiceChangeDelegate);
},_on_choiceChange:function(){var value=this._statusChoiseComponent.get_value();
var message=this._choiceDescriptions[value];
jQuery(this._messageLabel).text(message);
if(value==Telerik.Sitefinity.GenericContent.Model.ContentUIStatus.Scheduled){jQuery(this._datesPanel).show();
}else{jQuery(this._datesPanel).hide();
}},get_expirationDateComponent:function(){return this._expirationDateComponent;
},set_expirationDateComponent:function(value){this._expirationDateComponent=value;
},get_publicationDateComponent:function(){return this._publicationDateComponent;
},set_publicationDateComponent:function(value){this._publicationDateComponent=value;
},get_statusChoiseComponent:function(){return this._statusChoiseComponent;
},set_statusChoiseComponent:function(value){this._statusChoiseComponent=value;
},get_choiceDescriptions:function(){return this._choiceDescriptions;
},set_choiceDescriptions:function(value){this._choiceDescriptions=value;
},get_messageLabel:function(){return this._messageLabel;
},set_messageLabel:function(value){this._messageLabel=value;
},get_datesPanel:function(){return this._datesPanel;
},set_datesPanel:function(value){this._datesPanel=value;
},get_readModeLabel:function(){return this._readModeLabel;
},set_readModeLabel:function(value){this._readModeLabel=value;
}};
Telerik.Sitefinity.Web.UI.Fields.StatusField.registerClass("Telerik.Sitefinity.Web.UI.Fields.StatusField",Telerik.Sitefinity.Web.UI.Fields.CompositeFieldControl);
Type.registerNamespace("Telerik.Sitefinity.GenericContent.Model");
Telerik.Sitefinity.GenericContent.Model.ContentUIStatus=function(){};
Telerik.Sitefinity.GenericContent.Model.ContentUIStatus.prototype={Draft:0,PrivateCopy:1,Published:2,Scheduled:3};
Telerik.Sitefinity.GenericContent.Model.ContentUIStatus.registerEnum("Telerik.Sitefinity.GenericContent.Model.ContentUIStatus");
